import {it,expect,vi} from 'vitest';
import {once} from 'node:events';
import {randomUUID} from 'node:crypto';
import {mkdtemp} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createElement} from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {sparseSetup} from './sparse-fixture.js';
import {publicView,validateSave} from '../src/core/state.js';
import {handleAgentInput,executePlan,oneNavigation} from '../src/agent/executor.js';
import {fastPlan,validatePlan,createAgentPlan} from '../src/agent/planner.js';
import {blueprintSchema,type GoalInput} from '../src/agent/plan-schema.js';
import {handleSystemInput} from '../src/system/agent.js';
import {relationshipSummary,relationshipBadge,relationshipCondition} from '../src/shared/relationship.js';
import {panelRegistry,CharacterDetail} from '../src/client/panels.js';
import {JsonStore} from '../src/storage/json-store.js';
import {futureStatus,dueAssessment} from '../src/agent/future.js';
const A='我忘了我现在有多少钱了，而且我想知道我跟伊芙琳是什么关系。如果我们已经是比较熟的朋友，那我明天打算约她出去逛逛。';
const B='如果我和伊芙琳已经比较熟，明天放学后约她出去；如果还不够熟，就找她一起训练。';
async function fixture(score:number|null=50){
 const f=await sparseSetup();const save=await f.service.current(),npc=save.entities.find(e=>e.id!==save.player_state.entity_id&&e.components.character)!;
 npc.components.identity.name='伊芙琳';npc.components.character.role='熟悉的学习伙伴和朋友';npc.components.location=structuredClone(save.entities[0].components.location);
 npc.components.visual_assets={images:{fullbody:'evelyn_body'}};
 const player=save.entities.find(e=>e.id===save.player_state.entity_id)!;player.components.wallet={balances:{credit:356}};player.components.relationships={entries:score===null?{}:{[npc.id]:{familiarity:score,trust:25}}};
 save.last_turn={narrative:'当前场景保持不变',speaker:null,dialogue:null,choices:[],context_actions:[]};save.gm_state.notes='SECRET_ROMANCE_TRUE';await f.store.write(save);
 return {...f,npcId:npc.id,save,view:publicView(save)};
}
async function request(f:Awaited<ReturnType<typeof fixture>>,input:string){const s=await f.service.current();return handleAgentInput(f.service,{input,game_id:s.game_id,expected_revision:s.state_revision,request_id:randomUUID()});}
const goal=(id:string,type:GoalInput['type']='WORLD_QUERY',extra:Partial<GoalInput>={}):GoalInput=>({goal_id:id,type,normalized_goal:'我现在有多少钱？',depends_on:[],condition:null,branch:null,temporal_scope:{scope:'now',day_offset:0,window:'any'},target_entities:[],...extra});
it('single WORLD_QUERY preserves time, scene, RNG/event state and revision with zero AI calls',async()=>{const f=await fixture();const r=await request(f,'我现在有多少钱？');expect(r.message).toContain('356');expect(r.time_advanced).toBe(0);expect(await f.service.current()).toEqual(f.save);expect(f.calls).toHaveLength(0);});
it('two independent questions both execute and share one reply',async()=>{const f=await fixture();const r=await request(f,'我现在有多少钱，而且我想知道我跟伊芙琳是什么关系？');expect(r.results).toHaveLength(2);expect(r.results!.every(g=>g.status==='completed')).toBe(true);expect(r.message).toContain('356');expect(r.message).toContain('伊芙琳');expect(r.time_advanced).toBe(0);});
it('acceptance A has query dependency -> condition -> future without NPC action or time',async()=>{const f=await fixture();const turn=vi.spyOn(f.service,'turn');const r=await request(f,A);expect(r.plan!.goals.map(g=>g.type)).toEqual(['WORLD_QUERY','WORLD_QUERY','CONDITIONAL_INTENT','FUTURE_INTENT']);expect(r.plan!.dependencies).toEqual([{from:'g2',to:'g3'},{from:'g3',to:'g4'}]);expect(r.future_intents).toHaveLength(1);expect(r.future_intents![0].target_date).toBe(f.save.runtime.time.day+1);expect(turn).not.toHaveBeenCalled();const after=await f.service.current();expect(after.runtime.time).toEqual(f.save.runtime.time);expect(after.last_turn).toEqual(f.save.last_turn);expect(after.event_state).toEqual(f.save.event_state);expect(after.entities).toEqual(f.save.entities);expect(r.time_advanced).toBe(0);});
it('condition false never registers THEN future',async()=>{const f=await fixture(0);const r=await request(f,A);expect(r.plan!.goals[2].result!.condition).toBe(false);expect(r.results!.at(-1)!.status).toBe('skipped');expect((await f.service.current()).future_intents??[]).toHaveLength(0);});
it('acceptance B true only registers scheduled THEN after_school',async()=>{const f=await fixture();const turn=vi.spyOn(f.service,'turn');const r=await request(f,B);expect(r.future_intents).toHaveLength(1);expect(r.future_intents![0]).toMatchObject({target_date:2,time_window:'after_school'});expect(turn).not.toHaveBeenCalled();expect(r.results!.at(-1)!.status).toBe('skipped');});
it('B false executes only current ELSE attempt, not tomorrow THEN',async()=>{const f=await fixture(0);const turn=vi.spyOn(f.service,'turn').mockResolvedValue(f.view);const r=await request(f,B);expect(turn).toHaveBeenCalledTimes(1);expect((turn.mock.calls[0][0] as any).input).toContain('训练');expect(r.future_intents).toHaveLength(0);expect(r.results!.find(x=>x.goal_id==='g3')!.status).toBe('skipped');});
it('ELSE future registers only matching branch',async()=>{const f=await fixture(0);const r=await request(f,'如果我和伊芙琳已经比较熟，明天约她出去；如果还不够熟，明天找她一起训练。');expect(r.future_intents).toHaveLength(1);expect(r.future_intents![0].goal).toContain('训练');});
it('future/scheduled persistence survives JSON storage restart and export/import',async()=>{const f=await fixture();await request(f,'我明天下午放学后去找伊芙琳。');const save=await f.service.current(),dir=await mkdtemp(join(tmpdir(),'agf-plan-'));await new JsonStore(dir).write(save);expect((await new JsonStore(dir).read())!.future_intents).toEqual(save.future_intents);const exported=await f.service.export();await f.service.import(JSON.parse(exported));expect((await f.service.current()).future_intents).toEqual(save.future_intents);});
it('future and present action are distinct',async()=>{const f=await fixture();expect(fastPlan(f.view,'我明天想找伊芙琳。')!.goals[0].type).toBe('FUTURE_INTENT');expect(fastPlan(f.view,'我现在去找伊芙琳。')!.goals[0].type).toBe('WORLD_ACTION');});
it('result goal ids correspond exactly to plan and UI navigates once',async()=>{const f=await fixture();const r=await request(f,A);expect(r.results!.map(x=>x.goal_id)).toEqual(r.plan!.goals.map(x=>x.goal_id));expect(r.ui_actions.filter(a=>a.kind==='open_panel'||a.kind==='open_character_detail')).toHaveLength(1);expect(r.ui_actions[0]).toEqual({kind:'open_panel',panel:'relationships'});});
it('dependency failure skips dependent writes',async()=>{const f=await fixture();const plan=validatePlan({goals:[goal('a','WORLD_QUERY',{normalized_goal:'谁的关系？'}),goal('b','FUTURE_INTENT',{depends_on:['a'],temporal_scope:{scope:'future',day_offset:1,window:'any'}})]});const r=await executePlan(f.service,{input:'test',game_id:f.save.game_id,expected_revision:f.save.state_revision,request_id:randomUUID()},plan);expect(r.results!.map(x=>x.status)).toEqual(['failed','skipped']);expect((await f.service.current()).future_intents??[]).toHaveLength(0);});
it('cycles, missing dependencies and unguarded branches fail validation',()=>{expect(()=>validatePlan({goals:[goal('a','WORLD_QUERY',{depends_on:['b']}),goal('b','WORLD_QUERY',{depends_on:['a']})]})).toThrow('循环');expect(()=>validatePlan({goals:[goal('a','WORLD_QUERY',{depends_on:['missing']})]})).toThrow('依赖');expect(()=>validatePlan({goals:[goal('a','WORLD_ACTION',{branch:'then'})]})).toThrow('条件依赖');});
it('hidden romance is unresolved and never leaks to planner/condition',async()=>{const f=await fixture();const r=await request(f,'如果伊芙琳喜欢我，明天约她出去。');expect(r.message).toContain('无法确定');expect(r.future_intents).toHaveLength(0);expect(JSON.stringify(r)).not.toContain('SECRET_ROMANCE_TRUE');});
it('structured LLM fallback receives public state only and executes all goals',async()=>{const f=await fixture();const spy=vi.spyOn(f.ai.adapter,'generate').mockResolvedValue({data:{goals:[goal('one'),goal('two','WORLD_QUERY',{normalized_goal:'我和伊芙琳是什么关系？'})]}});const r=await request(f,'请分别核对财物总额以及该角色的人际情况');expect(r.results).toHaveLength(2);expect(spy.mock.calls[0][0].prompt).not.toContain('SECRET_ROMANCE_TRUE');expect(spy.mock.calls[0][0].threadId).toBeUndefined();expect(r.time_advanced).toBe(0);});
it('invalid LLM plan cannot modify state',async()=>{const f=await fixture();vi.spyOn(f.ai.adapter,'generate').mockResolvedValue({data:{goals:[{...goal('bad'),wallet_delta:1000}]}});await expect(request(f,'综合处理这些事项')).rejects.toThrow();expect(await f.service.current()).toEqual(f.save);});
it('future intent can be listed and cancelled by entity/date without id',async()=>{const f=await fixture();await request(f,'我明天想找伊芙琳。');expect((await request(f,'查看我的未来计划')).future_intents).toHaveLength(1);await request(f,'算了，我明天不找伊芙琳了。');expect((await f.service.current()).future_intents![0].status).toBe('cancelled');});
it('due and expiration are state-derived and never manufacture completion',async()=>{const f=await fixture();await request(f,'我明天下午放学后找伊芙琳。');const s=await f.service.current(),i=s.future_intents![0];expect(futureStatus(i,{day:2,minute:900})).toBe('planned');expect(futureStatus(i,{day:2,minute:960})).toBe('due');expect(futureStatus(i,{day:3,minute:0})).toBe('expired');s.runtime.time={day:2,minute:960};const due=validateSave(s);expect(due.future_intents![0].status).toBe('due');expect(dueAssessment(publicView(due),due.future_intents![0])).toContain('尚未发生');expect(due.last_turn).toEqual(f.save.last_turn);});
it('repeated request does not duplicate future plan',async()=>{const f=await fixture(),body={input:A,game_id:f.save.game_id,expected_revision:f.save.state_revision,request_id:randomUUID()};const a=await handleAgentInput(f.service,body),b=await handleAgentInput(f.service,body);expect(b).toEqual(a);expect((await f.service.current()).future_intents).toHaveLength(1);});
it('stale revision refuses all plan writes',async()=>{const f=await fixture();await expect(handleAgentInput(f.service,{input:A,game_id:f.save.game_id,expected_revision:999,request_id:randomUUID()})).rejects.toThrow('状态已更新');expect(await f.service.current()).toEqual(f.save);});
it('acceptance C asks then resolves the next reply in the same System session',async()=>{const f=await fixture();const a=await handleSystemInput(f.service,{input:'我想改一个人物头像。'});expect(a.session!.status).toBe('waiting_for_clarification');const b=await handleSystemInput(f.service,{input:'伊芙琳。',session_id:a.session!.session_id});expect(b.session!.session_id).toBe(a.session!.session_id);expect(b.directive).toMatchObject({kind:'open_crop_editor',entity_id:f.npcId,source_asset_id:'evelyn_body'});expect(b.session!.status).toBe('completed');expect(await f.service.current()).toEqual(f.save);});
it('System cancellation prevents old goal contamination',async()=>{const f=await fixture();const a=await handleSystemInput(f.service,{input:'我想修改一个人物头像。'});const b=await handleSystemInput(f.service,{input:'取消'});expect(b.session!.status).toBe('cancelled');expect(b.session!.session_id).toBe(a.session!.session_id);const c=await handleSystemInput(f.service,{input:'伊芙琳。'});expect(c.directive).toBeUndefined();expect(c.session!.session_id).not.toBe(a.session!.session_id);});
it('completed System request is followed by a new session',async()=>{const f=await fixture();const a=await handleSystemInput(f.service,{input:'改一下伊芙琳的头像'});const b=await handleSystemInput(f.service,{input:'这个界面太挤了。'});expect(b.session!.session_id).not.toBe(a.session!.session_id);expect(b.category).toBe('PRODUCT_FEEDBACK');});
it('duplicate names require clarification instead of choosing first entity',async()=>{const f=await fixture();const s=await f.service.current();const npc=structuredClone(s.entities.find(e=>e.id===f.npcId)!);npc.id='another_evelyn';s.entities.push(npc);await f.store.write(s);const a=await handleSystemInput(f.service,{input:'修改伊芙琳头像'});expect(a.session!.status).toBe('waiting_for_clarification');expect(a.directive).toBeUndefined();const b=await handleSystemInput(f.service,{input:'第二位'});expect(b.directive?.entity_id).toBe('another_evelyn');});
it('profile relationships agree across Agent, cards, detail and relationships panel',async()=>{const f=await fixture(null),npc=f.view.entities.find(e=>e.id===f.npcId)!;const summary=relationshipSummary(f.view,npc);expect(summary.source).toBe('profile');expect(relationshipCondition(f.view,npc)).toBe(true);const r=await request(f,'我跟伊芙琳是什么关系？');expect(r.message).toContain(summary.text);const props={view:f.view,busy:false,act:()=>{}};expect(renderToStaticMarkup(createElement(panelRegistry.relationships,props))).toContain(summary.text);expect(renderToStaticMarkup(createElement(CharacterDetail,{...props,entity:npc}))).toContain(summary.text);expect(renderToStaticMarkup(createElement(panelRegistry.characters,props))).toContain(relationshipBadge(f.view,npc));});
it('graph takes precedence over familiar profile wording',async()=>{const f=await fixture(0);expect(relationshipCondition(f.view,f.view.entities.find(e=>e.id===f.npcId)!)).toBe(false);});
it('condition action cannot preempt pending foreground choice',async()=>{const f=await fixture();const s=await f.service.current();s.last_turn!.choices=['回答'];await f.store.write(s);const turn=vi.spyOn(f.service,'turn');const r=await request(f,'如果伊芙琳现在在这里，我就邀请她。');expect(turn).not.toHaveBeenCalled();expect(r.plan!.status).toBe('partial');});

it('HTTP acceptance A/B/C uses real routing and preserves canonical world for planning',async()=>{
 const f=await fixture(),directory=await mkdtemp(join(tmpdir(),'agf-agent-http-'));const {createApp}=await import('../src/server/app.js');
 const server=createApp(f.service,undefined,undefined,join(directory,'assets')).listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+(server.address() as any).port;
 try{
  const token=(await(await fetch(base+'/api/session')).json()).token;
  const post=async(path:string,body:unknown)=>{const response=await fetch(base+'/api/'+path,{method:'POST',headers:{'Content-Type':'application/json','X-Game-Token':token},body:JSON.stringify(body)});expect(response.status).toBe(200);return response.json();};
  const input=async(text:string)=>{const s=await f.service.current();return post('input',{input:text,request_id:randomUUID(),game_id:s.game_id,expected_revision:s.state_revision});};
  const a=await input(A);expect(a.message).toContain('356');expect(a.message).toContain('伊芙琳');expect(a.future_intents).toHaveLength(1);expect(a.time_advanced).toBe(0);
  const b=await input(B);expect(b.future_intents[0].time_window).toBe('after_school');expect(b.results.at(-1).status).toBe('skipped');
  const c1=await post('system',{input:'我想改一个人物头像。'}),c2=await post('system',{input:'伊芙琳。',session_id:c1.session.session_id});expect(c2.session.session_id).toBe(c1.session.session_id);expect(c2.directive.kind).toBe('open_crop_editor');
  const s=await f.service.current();expect(s.last_turn).toEqual(f.save.last_turn);expect(s.runtime.time).toEqual(f.save.runtime.time);expect(s.entities).toEqual(f.save.entities);expect(f.calls).toHaveLength(0);
 }finally{server.closeAllConnections();await new Promise<void>(resolve=>server.close(()=>resolve()));}
});
it('due execution checks current availability before calling AI or changing state',async()=>{const f=await fixture();await request(f,'我明天想找伊芙琳。');const s=await f.service.current();s.runtime.time={day:2,minute:960};s.entities.find(e=>e.id===f.npcId)!.components.location.location_id='station';await f.store.write(s);const r=await request(f,'执行找伊芙琳的计划');expect(r.plan!.status).toBe('partial');expect(f.calls).toHaveLength(0);expect((await f.service.current()).future_intents![0].status).toBe('due');});
it('future completion requires actual committed attempt, not player declaration or due time',async()=>{const f=await fixture();await request(f,'我明天想找伊芙琳。');const s=await f.service.current();s.runtime.time={day:2,minute:960};await f.store.write(s);
 vi.spyOn(f.ai.adapter,'generate').mockImplementation(async r=>r.role==='intent_interpreter'?{data:{type:'TALK',target_id:f.npcId,parameters_json:JSON.stringify({topic:'邀请一起逛街'}),clarification:null}}:{data:{narrative:'你尝试发出了邀请。',speaker:f.npcId,dialogue:'我还需要考虑。',choices:[],patches:[]}});
 const r=await request(f,'执行找伊芙琳的计划');expect(r.plan!.status).toBe('completed');const after=await f.service.current();expect(after.future_intents![0].status).toBe('completed');expect(after.future_intents![0].completed_by_request).not.toBeNull();expect(after.runtime.receipts.some(x=>x.id===after.future_intents![0].completed_by_request)).toBe(true);expect(r.message).toContain('不代表约会');expect(after.last_turn!.dialogue).toContain('考虑');
});
it('System confirmation continues the selected destructive task rather than rerouting yes',async()=>{const f=await fixture();const a=await handleSystemInput(f.service,{input:'彻底移除商店系统'});expect(a.session!.status).toBe('waiting_for_confirmation');const b=await handleSystemInput(f.service,{input:'确认',session_id:a.session!.session_id});expect(b.session!.status).toBe('completed');expect(b.message).toContain('已移除');});
it('structured planner can execute a query then a real ordinary action in one plan',async()=>{const f=await fixture();vi.spyOn(f.ai.adapter,'generate').mockImplementation(async r=>{
 if(JSON.stringify(r.schema).includes('normalized_goal'))return {data:{goals:[goal('money'),goal('wait','WORLD_ACTION',{normalized_goal:'等一分钟',depends_on:['money']})]}};
 if(r.role==='intent_interpreter')return {data:{type:'WAIT',target_id:null,parameters_json:'{"minutes":1}',clarification:null}};
 return {data:{narrative:'等待一分钟。',speaker:null,dialogue:null,choices:[],patches:[]}};
 });const r=await request(f,'核对金额后，再停留片刻');expect(r.results!.every(g=>g.status==='completed')).toBe(true);expect(r.message).toContain('356');expect(r.time_advanced).toBe(1);});

it('quoted future speech remains a current utterance, not a saved future intent',async()=>{const f=await fixture();const p=fastPlan(f.view,'我对伊芙琳说：明天我们再见。')!;expect(p.goals).toHaveLength(1);expect(p.goals[0].type).toBe('WORLD_SPEECH');expect(p.goals[0].temporal_scope.scope).toBe('now');});

it('single-query clarification preserves the legacy AgentResult field',async()=>{const f=await fixture();const r=await request(f,'我跟谁是什么关系？');expect(r.clarification).toBe('which_entity');expect(r.time_advanced).toBe(0);});
