import {describe,it,expect} from 'vitest';
import {randomUUID} from 'node:crypto';
import {fresh,MemoryStore} from './helpers.js';
import {validateSave,publicView} from '../src/core/state.js';
import {worldImage,checkpointTurn} from '../src/core/turn-history.js';
import {commitTruth,ensureHiddenTruth,registerEvidence} from '../src/narrative/truth.js';
import {addArc,applyStoryCommand,completeSaga,deathOutcomeAllowed,ensureNarrativeState,evaluateDirector,invalidateDirectorPlan,mergeArcs,noteMeaningfulTurn,observeCanonicalTurn,payoffSetup,recordCharacterArcEvent,recordSetup,transitionArc} from '../src/narrative/runtime.js';
import {buildNarrativeContext} from '../src/narrative/context.js';
import {defaultRoleplayConfig,suggestLifeHorizon} from '../src/narrative/policy.js';
import {GameService} from '../src/server/service.js';
import {AIRuntime} from '../src/ai/runtime.js';
import type {NarrativeArc} from '../src/narrative/schema.js';

const arc=(id:string,status:NarrativeArc['status']='ACTIVE',eventRefs:string[]=[],truthRefs:string[]=[]):NarrativeArc=>({id,title:`故事 ${id}`,status,summary:'来自真实世界的故事线',canonical_event_refs:eventRefs,truth_refs:truthRefs,participant_refs:[],closure_priority:.4,reveal_step:0,accelerated_closure:false,last_meaningful_revision:0});
const event=(save:ReturnType<typeof fresh>)=>{const request_id=randomUUID();save.action_facts=[...(save.action_facts??[]),{request_id,actor_id:save.player_state.entity_id,target_id:null,input:'调查',facts:['发生了一件可验证的事'],time:structuredClone(save.runtime.time)}];return request_id;};

describe('narrative architecture and compatibility',()=>{
 it('loads a v0.1.16-shaped save and lazily initializes without inventing a story',()=>{const save=fresh();delete save.narrative_state;delete save.definition.roleplay_config;delete save.gm_state.hidden_truth;delete save.definition.gm_state.hidden_truth;const parsed=validateSave(save);expect(parsed.narrative_state).toBeUndefined();const state=ensureNarrativeState(parsed);expect(state.arcs).toEqual([]);expect(state.current_saga).toBeNull();});
 it('keeps age and canonical history out of narrative state',()=>{const save=fresh(),state=ensureNarrativeState(save);expect(state).not.toHaveProperty('current_age');expect(JSON.stringify(state)).not.toContain('narrative_history');expect(state.player_entity_ref).toBe(save.player_state.entity_id);});
 it('builds a bounded context by reference and includes only explicitly relevant private truth',()=>{const save=fresh();const truth=ensureHiddenTruth(save);truth.commitments.push({id:'hidden_a',commitment:'HARD_TRUTH',statement:'A是真相',seed_constraint:null,source:'GM_DECLARED',created_event_ref:null,evidence:[],known_by:[]},{id:'hidden_b',commitment:'HARD_TRUTH',statement:'B是真相',seed_constraint:null,source:'GM_DECLARED',created_event_ref:null,evidence:[],known_by:[]});const context=buildNarrativeContext(save,['hidden_a']);expect(context.relevant_hidden_truth.map(x=>x.id)).toEqual(['hidden_a']);expect(context).not.toHaveProperty('entities');expect(context).not.toHaveProperty('history');});
 it('never projects hidden truth to the player view',()=>{const save=fresh();ensureHiddenTruth(save).commitments.push({id:'secret',commitment:'HARD_TRUTH',statement:'幕后答案',seed_constraint:null,source:'GM_DECLARED',created_event_ref:null,evidence:[],known_by:[]});expect(JSON.stringify(publicView(save))).not.toContain('幕后答案');});
 it('world snapshots include narrative organization so undo restores it atomically',()=>{const before=fresh(),after=structuredClone(before);addArc(after,arc('atomic'));after.state_revision++;checkpointTurn(before,after,randomUUID());expect(worldImage(after)).toHaveProperty('narrative_state');const restored=structuredClone(after.turn_checkpoint!.before) as any;expect(restored.narrative_state.arcs).toEqual([]);});
});

describe('truth and evidence integrity',()=>{
 it('does not let a player hypothesis rewrite a hard truth',()=>{const save=fresh();commitTruth(save,{id:'origin',commitment:'HARD_TRUTH',statement:'感染来自人类实验事故',seed_constraint:null,source:'WORLD_CREATION',created_event_ref:null,evidence:[],known_by:[]});expect(()=>commitTruth(save,{id:'origin',commitment:'HARD_TRUTH',statement:'感染来自外星人',seed_constraint:null,source:'GM_DECLARED',created_event_ref:null,evidence:[],known_by:[]})).toThrow('不能被重写');expect(ensureHiddenTruth(save).commitments.find(x=>x.id==='origin')?.statement).toContain('人类实验');});
 it('requires evidence to pre-exist or cite a causal world event',()=>{const save=fresh();commitTruth(save,{id:'origin',commitment:'HARD_TRUTH',statement:'固定答案',seed_constraint:null,source:'WORLD_CREATION',created_event_ref:null,evidence:[],known_by:[]});expect(()=>registerEvidence(save,'origin',{id:'usb',status:'CAUSALLY_CREATED',description:'临时出现的USB',event_ref:null,discovered_by:[]})).toThrow('真实世界事件');const ref=event(save);registerEvidence(save,'origin',{id:'sample',status:'CAUSALLY_CREATED',description:'事故后取得的样本',event_ref:ref,discovered_by:[]});expect(ensureHiddenTruth(save).commitments.find(item=>item.id==='origin')!.evidence[0].event_ref).toBe(ref);});
 it('save/reload and undo snapshots preserve exactly the same hidden answer',()=>{const before=fresh();commitTruth(before,{id:'answer',commitment:'HARD_TRUTH',statement:'答案X',seed_constraint:null,source:'WORLD_CREATION',created_event_ref:null,evidence:[],known_by:[]});const roundtrip=validateSave(JSON.parse(JSON.stringify(before)));expect(roundtrip.gm_state.hidden_truth).toEqual(before.gm_state.hidden_truth);const after=structuredClone(before);after.runtime.time.minute++;checkpointTurn(before,after,randomUUID());expect((after.turn_checkpoint!.before.gm_state as any).hidden_truth).toEqual(before.gm_state.hidden_truth);});
});

describe('roleplay policy, arc capacity and lifecycle',()=>{
 it('suggests a world-aware soft horizon rather than a death date',()=>{expect(suggestLifeHorizon({species:'长寿精灵',premise:'魔法学院'})).toMatchObject({kind:'ai_suggested',target_age_min:200,target_age_max:300});expect(suggestLifeHorizon({species:'人类',premise:'现代城市'})).not.toHaveProperty('death_age');});
 it('narrative-standard death rejects meaningless random death but allows chosen lethal risk and progression',()=>{const config=defaultRoleplayConfig();expect(deathOutcomeAllowed(config,{explicit_extreme_risk:false,long_term_lethal_progression:false,ordinary_unwarned_accident:true})).toBe(false);expect(deathOutcomeAllowed(config,{explicit_extreme_risk:true,long_term_lethal_progression:false,ordinary_unwarned_accident:false})).toBe(true);expect(deathOutcomeAllowed(config,{explicit_extreme_risk:false,long_term_lethal_progression:true,ordinary_unwarned_accident:false})).toBe(true);});
 it('uses a soft cap: a fourth real arc emerges and can be activated by player confirmation',()=>{const save=fresh();for(const id of ['a','b','c'])addArc(save,arc(id));const fourth=addArc(save,arc('d'));expect(fourth.status).toBe('EMERGING');applyStoryCommand(save,'OVERLOAD_CONFIRMATION');expect(fourth.status).toBe('ACTIVE');});
 it('supports dormant/reactivate, abandoned, failed and accelerated closure without deleting the arc',()=>{const save=fresh();addArc(save,arc('life'));applyStoryCommand(save,'DORMANT');expect(save.narrative_state!.arcs[0].status).toBe('DORMANT');applyStoryCommand(save,'REACTIVATE');expect(save.narrative_state!.arcs[0].status).toBe('ACTIVE');applyStoryCommand(save,'ACCELERATE_CLOSURE');expect(save.narrative_state!.arcs[0]).toMatchObject({status:'CONVERGING',accelerated_closure:true});transitionArc(save,'life','FAILED');expect(save.narrative_state!.arcs[0].status).toBe('FAILED');});
 it('raises closure directives at capacity without preventing the world event',()=>{const save=fresh();for(const id of ['a','b','c'])addArc(save,arc(id));addArc(save,arc('earthquake'));const decision=evaluateDirector(save,'MAJOR_WORLD_EVENT');expect(save.narrative_state!.arcs.some(a=>a.id==='earthquake')).toBe(true);expect(decision.directives.some(d=>d.kind==='CLOSURE_OPPORTUNITY')).toBe(true);});
 it('evaluates ordinary narrative cadence locally without an additional provider call',()=>{const save=fresh();for(let index=0;index<6;index++)noteMeaningfulTurn(save);expect(save.narrative_state!.recent_director_decisions).toHaveLength(1);expect(save.narrative_state!.meaningful_turns_since_evaluation).toBe(0);});
 it('forms story focus only from a committed significant event and leaves quiet life alone',()=>{const save=fresh(),quiet=event(save);expect(observeCanonicalTurn(save,quiet,['吃了一顿普通午饭。'])).toBeNull();expect(save.narrative_state!.current_saga).toBeNull();const important=event(save),created=observeCanonicalTurn(save,important,['发现港口失踪事件留下的重要证据。']);expect(created?.canonical_event_refs).toEqual([important]);expect(save.narrative_state!.current_saga?.canonical_event_refs).toEqual([important]);});
});

describe('story craft remains grounded in canonical history',()=>{
 it('records setup/payoff and character change only with real event references',()=>{const save=fresh(),first=event(save),second=event(save);addArc(save,arc('growth'));recordSetup(save,{id:'photo',label:'奇怪照片',source_event_ref:first,arc_ref:'growth'});payoffSetup(save,'photo',second);recordCharacterArcEvent(save,'growth',save.player_state.entity_id,second);expect(save.narrative_state!.unpaid_setups[0]).toMatchObject({status:'PAID_OFF',payoff_event_ref:second});expect(()=>recordSetup(save,{id:'fake',label:'虚构伏笔',source_event_ref:'missing'})).toThrow('真实历史');});
 it('invalidates an obsolete beat and produces a replan when an NPC acts first',()=>{const save=fresh();addArc(save,arc('mystery'));evaluateDirector(save,'MEANINGFUL_TURNS');const decision=invalidateDirectorPlan(save,'NPC B 已经先发现证据，旧的首次发现计划失效');expect(decision?.directives[0].kind).toBe('REPLAN');expect(decision?.invalidated_decision_revisions).toHaveLength(1);});
 it('merges arcs only when they share a real causal event or truth',()=>{const save=fresh(),ref=event(save);addArc(save,arc('infection','ACTIVE',[ref]));addArc(save,arc('signal','ACTIVE',[ref]),true);mergeArcs(save,'infection',['signal']);expect(save.narrative_state!.arcs.find(a=>a.id==='signal')?.status).toBe('CLOSED');const unrelated=addArc(save,arc('unrelated'),true);expect(()=>mergeArcs(save,'infection',[unrelated.id])).toThrow('因果');});
 it('completes a saga from referenced history while retaining unresolved consequences and continuing the world',()=>{const save=fresh(),ref=event(save),state=ensureNarrativeState(save);addArc(save,arc('case','FAILED',[ref]));state.current_saga={id:'saga_one',title:'第一篇章',start_time:{day:1,minute:0},phase:'AFTERMATH',arc_refs:['case'],canonical_event_refs:[ref]};const record=completeSaga(save,{outcome:'调查失败，但世界保留了后果',continuation_hooks:['以后可能重查']});expect(record.unresolved_arc_refs).toEqual(['case']);expect(save.narrative_state!.current_saga).toBeNull();expect(save.runtime.time).toEqual({day:1,minute:540});});
 it('open-ended and immortal horizons still permit saga completion',()=>{for(const kind of ['open_ended','immortal'] as const){const save=fresh(),ref=event(save);save.definition.roleplay_config!.life_horizon={kind,target_age_min:null,target_age_max:null,basis:'测试'};const state=ensureNarrativeState(save);addArc(save,arc('closed','CLOSED',[ref]));state.current_saga={id:`saga_${kind}`,title:'阶段故事',start_time:{day:1,minute:0},phase:'AFTERMATH',arc_refs:['closed'],canonical_event_refs:[ref]};expect(completeSaga(save,{outcome:'阶段完成'}).title).toBe('阶段故事');}});
});

describe('service persistence',()=>{
 it('story management is revisioned, receipt-deduplicated and undoable',async()=>{const save=fresh();addArc(save,arc('service_arc'));const store=new MemoryStore();await store.write(validateSave(save));const ai=new AIRuntime({name:'fixture',generate:async()=>{throw Error('unused')}});const service=new GameService(store,ai,save.definition);const request_id=randomUUID();const first=await service.narrativeCommand({request_id,game_id:save.game_id,expected_revision:save.state_revision},'DORMANT');expect(first.view.story?.major_arcs[0].status).toBe('DORMANT');const duplicate=await service.narrativeCommand({request_id,game_id:save.game_id,expected_revision:save.state_revision},'DORMANT');expect(duplicate.view.revision).toBe(first.view.revision);await service.undo({request_id:randomUUID(),game_id:save.game_id,expected_revision:first.view.revision});expect((await service.view())!.story?.major_arcs[0].status).toBe('ACTIVE');});
 it('advanced diagnostics expose truth counts but never secret prose',async()=>{const save=fresh();save.gm_state.hidden_truth={version:1,commitments:[{id:'secret',commitment:'HARD_TRUTH',statement:'NEVER_EXPOSE_THIS',seed_constraint:null,source:'GM_DECLARED',created_event_ref:null,evidence:[],known_by:[]}]};const store=new MemoryStore();await store.write(save);const service=new GameService(store,new AIRuntime({name:'fixture',generate:async()=>{throw Error('unused')}}),save.definition);const debug=await service.narrativeDebug();expect(debug.hidden_truth_summary.count).toBe(1);expect(JSON.stringify(debug)).not.toContain('NEVER_EXPOSE_THIS');});
});
