import {it,expect} from 'vitest';import {randomUUID} from 'node:crypto';import {mkdtemp,rm,readFile} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {RoutineJobs} from '../src/routine/jobs.js';import {sparseSetup,sparsePlan,sparseWorld} from './sparse-fixture.js';import {absoluteTime,dateAt,calendarDay} from '../src/routine/calendar.js';import {sparseStep,routineOf} from '../src/routine/scheduler.js';import {validateReferences} from '../src/routine/grounding.js';import {displayText} from '../src/shared/display.js';import {publicView} from '../src/core/state.js';import {migrateInstalledWorld} from '../src/routine/migration.js';import {GameService} from '../src/server/service.js';import {JsonStore} from '../src/storage/json-store.js';import {AIRuntime} from '../src/ai/runtime.js';
async function envelope(service:GameService,type='START_ROUTINE'){const s=await service.current();return {request_id:randomUUID(),game_id:s.game_id,expected_revision:s.state_revision,action:{type,parameters:type==='START_ROUTINE'?{label:'正常生活',pattern:'每天睡眠、上课、训练和固定兼职'}:{}}};}
async function finished(jobs:RoutineJobs,id:string){for(let i=0;i<1000;i++){const j=(await jobs.get(id))!;if(!['queued','running'].includes(j.status))return j;await new Promise(r=>setTimeout(r,2));}throw Error('job did not finish');}
it('one day and a week run locally, compiler once, zero simulation AI calls',async()=>{const {service,calls}=await sparseSetup();const jobs=new RoutineJobs(service);const t=performance.now();const one=await finished(jobs,(await jobs.start(await envelope(service))).job_id);expect(one.status).toBe('completed');expect(one.metrics.compiler_calls).toBe(1);expect(one.metrics.ai_requests).toBe(1);expect((await service.current()).runtime.time).toEqual({day:2,minute:0});
 const week=await finished(jobs,(await jobs.start({...await envelope(service,'CONTINUE_ROUTINE'),max_days:7})).job_id);expect(week.status).toBe('completed');expect(week.metrics.ai_requests).toBe(0);expect(week.metrics.compiler_calls).toBe(0);expect(calls).toHaveLength(1);expect((await service.current()).runtime.time).toEqual({day:9,minute:0});expect(performance.now()-t).toBeLessThan(45000);

 const player=(await service.current()).entities.find(e=>e.id==='player')!;expect((player.components.skills.entries as any).study.xp).toBe(24);expect((player.components.wallet.balances as any).credit).toBe(164);
},45000);
it('sleep, course, fixed movement and training are separate meaningful local steps',async()=>{const {service,ai}=await sparseSetup();await service.turn(await envelope(service),undefined,undefined,undefined,true);let s=await service.current();const start=absoluteTime(s);const metrics=ai.metrics.requests;s=await sparseStep(s,ai,start+1440);expect(s.runtime.time.minute).toBe(480);expect(s.entities.find(e=>e.id==='player')!.components.condition.stamina).toBe(66);s=await sparseStep(s,ai,start+1440);expect(s.runtime.time.minute).toBe(522);s=await sparseStep(s,ai,start+1440);expect(s.runtime.time.minute).toBe(540);expect(s.entities.find(e=>e.id==='player')!.components.location.location_id).toBe('station');s=await sparseStep(s,ai,start+1440);expect(s.runtime.time.minute).toBe(720);expect(ai.metrics.requests).toBe(metrics);});
it('fixed future task cuts ordinary work at its exact hard boundary',async()=>{const {service,store}=await sparseSetup();const s=await service.current();s.routine_meta!.scheduled_tasks=[{id:'volunteer',label:'志愿任务',at:1440+600,window:'exact',status:'accepted',source:'confirmed schedule',resolved:false}];
await store.write(s);const jobs=new RoutineJobs(service);const job=await finished(jobs,(await jobs.start(await envelope(service))).job_id);expect(job.status).toBe('interrupted');expect((await service.current()).runtime.time.minute).toBe(600);expect(job.message).toContain('志愿任务');});
it('unknown calendar pauses without consuming time, compiler plan remains reusable',async()=>{const {service,store,calls}=await sparseSetup();const s=await service.current();delete s.calendar;delete s.definition.calendar;await store.write(s);const before=s.runtime.time;const jobs=new RoutineJobs(service);const job=await finished(jobs,(await jobs.start(await envelope(service))).job_id);expect(job.status).toBe('interrupted');expect((await service.current()).runtime.time).toEqual(before);expect(routineOf(await service.current()).plan).toBeTruthy();expect(calls).toHaveLength(1);});
it('calendar anchors map weekdays and month transitions with explicit lengths',()=>{const c=sparseWorld().calendar!;expect(dateAt(c,32)).toMatchObject({month:2,day:1,weekday:4});expect(calendarDay(c,3,6)).toBe(65);expect(dateAt({...c,anchor_day:62,anchor_month:3,anchor_date:3,anchor_weekday:3},63)).toMatchObject({month:3,day:4,weekday:4});});
it('display names replace known entity IDs even adjacent to Chinese, unknown IDs get safe fallback',async()=>{const {service}=await sparseSetup();const s=await service.current();s.last_turn={narrative:'player与npc_lin交流，unknown_project不可见。',speaker:null,dialogue:null,choices:[],context_actions:[]};const v=publicView(s);expect(v.last_turn!.narrative).toContain('林舟');expect(v.last_turn!.narrative).not.toContain('npc_lin');expect(v.last_turn!.narrative).not.toContain('unknown_project');expect(v.entities.find(e=>e.id==='player')).toBeTruthy();});
it('noncanonical task/project/activity references are rejected',async()=>{const {service}=await sparseSetup();const s=await service.current();expect(()=>validateReferences(s,{entity_ids:['player'],task_ids:[],activity_ids:['invented_project']})).toThrow('不存在');expect(()=>validateReferences(s,{entity_ids:[],task_ids:['invented_task'],activity_ids:[]})).toThrow('不存在');});
it('known map migration is idempotent and never rewrites player canonical data',async()=>{const {service}=await sparseSetup();const s=await service.current();const original=structuredClone(s);const world=structuredClone(s.definition);world.map!.locations.push({id:'region',name:'地区',description:'既有地区',tags:[],parent_id:null,position:{x:50,y:50}});for(const l of world.map!.locations)if(l.id!=='region')l.parent_id='region';
const packs=[{world,legacy_maps:[structuredClone(original.definition.map)]}];const migrated=migrateInstalledWorld(s,packs).save;expect(migrated.entities).toEqual(original.entities);expect(migrated.gm_state).toEqual(original.gm_state);expect(migrated.runtime).toEqual(original.runtime);expect(migrated.definition.map).toEqual(world.map);expect(migrateInstalledWorld(migrated,packs).changed).toBe(false);});
it('user cancellation is a non-error terminal job and late AI output cannot commit',async()=>{let release!:()=>void;const {service,store}=await sparseSetup(async()=>{await new Promise<void>(r=>release=r);return {data:sparsePlan};});const jobs=new RoutineJobs(service);const before=await service.current();const job=await jobs.start(await envelope(service));for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,2));await jobs.cancel(job.job_id);release();const result=await finished(jobs,job.job_id);expect(result.status).toBe('cancelled');expect(result.message).not.toContain('aborted');expect((await service.current()).runtime).toEqual(before.runtime);expect((await service.current()).state_revision).toBe(before.state_revision);});
it('browser polling can recover a running job; restarting server cancels unfinished work without replay',async()=>{const dir=await mkdtemp(join(tmpdir(),'agf-jobs-'));try{const {service}=await sparseSetup();let release!:()=>void;(service.ai.adapter as any).generate=async()=>{await new Promise<void>(r=>release=r);return {data:sparsePlan}};const jobs=new RoutineJobs(service,dir);const job=await jobs.start(await envelope(service));for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,2));expect((await jobs.get())!.job_id).toBe(job.job_id);await jobs.cancel(job.job_id);release();await finished(jobs,job.job_id);const saved=JSON.parse(await readFile(join(dir,'routine-jobs.json'),'utf8'));saved[0].status='running';const {writeFile}=await import('node:fs/promises');await writeFile(join(dir,'routine-jobs.json'),JSON.stringify(saved));const recovered=new RoutineJobs(service,dir);expect((await recovered.get(job.job_id))!.status).toBe('cancelled');}finally{await rm(dir,{recursive:true,force:true});}},15000);
it('routine plan and local outcomes survive a real JsonStore/service replacement',async()=>{const dir=await mkdtemp(join(tmpdir(),'agf-save-'));try{const service=new GameService(new JsonStore(dir),new AIRuntime({name:'compiler',generate:async()=>({data:sparsePlan})}),sparseWorld());await service.newGame();const jobs=new RoutineJobs(service,dir);await finished(jobs,(await jobs.start(await envelope(service))).job_id);const before=await service.current();const restarted=new GameService(new JsonStore(dir),new AIRuntime({name:'offline',generate:async()=>{throw Error('no calls')}}),sparseWorld());expect(await restarted.current()).toEqual(before);const more=new RoutineJobs(restarted,dir);expect((await finished(more,(await more.start(await envelope(restarted,'CONTINUE_ROUTINE'))).job_id)).status).toBe('completed');}finally{await rm(dir,{recursive:true,force:true});}},20000);


it('full work split across job horizons pays exactly once',async()=>{const {service,store,ai}=await sparseSetup();await service.turn(await envelope(service),undefined,undefined,undefined,true);let s=await service.current();s.runtime.time.minute=960;s.entities.find(e=>e.id==='player')!.components.location.location_id='station';const balance=Number((s.entities.find(e=>e.id==='player')!.components.wallet.balances as any).credit);s=await sparseStep(s,ai,1440+1020);expect(Number((s.entities.find(e=>e.id==='player')!.components.wallet.balances as any).credit)).toBe(balance);s=await sparseStep(s,ai,1440+1080);expect(Number((s.entities.find(e=>e.id==='player')!.components.wallet.balances as any).credit)).toBe(balance+8);});
it('provider timeout is failed, not user cancellation, and does not commit',async()=>{const {service}=await sparseSetup(async()=>{throw new DOMException('provider timed out','TimeoutError')});const before=await service.current();const jobs=new RoutineJobs(service);const job=await finished(jobs,(await jobs.start(await envelope(service))).job_id);expect(job.status).toBe('failed');expect(job.message).toContain('超时');expect((await service.current()).state_revision).toBe(before.state_revision);});
it('job request is idempotent and another writer cannot enter its lease',async()=>{let release!:()=>void;const {service}=await sparseSetup(async()=>{await new Promise<void>(r=>release=r);return {data:sparsePlan}});const jobs=new RoutineJobs(service);const req=await envelope(service);const first=await jobs.start(req);expect((await jobs.start(req)).job_id).toBe(first.job_id);await expect(service.checkpoint()).rejects.toThrow('后台生活');for(let i=0;i<100&&!release;i++)await new Promise(r=>setTimeout(r,2));await jobs.cancel(first.job_id);release();await finished(jobs,first.job_id);expect(service.routineLease).toBeNull();});
it('plan rejects nonexistent social candidates and overlapping blocks',async()=>{const {service,ai}=await sparseSetup();await service.turn(await envelope(service),undefined,undefined,undefined,true);const s=await service.current();const plan=routineOf(s).plan as any;plan.blocks[0].candidate_ids=['missing_person'];const {validateSave}=await import('../src/core/state.js');expect(()=>validateSave(s)).toThrow('人物');plan.blocks[0].candidate_ids=[];plan.blocks[1].start_minute=100;expect(()=>validateSave(s)).toThrow('重叠');});
