import { z } from 'zod';
import { contextActionSchema, id, narrativeSchema, providerEmptyArray } from '../core/schema.js';
import {backgroundIncidentSchema,worldMacroArcSchema} from '../background/schema.js';
export type AIRole = 'world_initializer' | 'intent_interpreter' | 'narrator' | 'gm_reasoning' | 'routine_compiler';
export interface AIRequest { role: AIRole; prompt: string; schema: unknown; threadId?: string; signal?: AbortSignal; maxOutputTokens?: number }
export interface AIResult { data: unknown; threadId?: string; recovered?: boolean; usage?: {input_tokens:number;output_tokens:number} }
export interface AIAdapter {
  readonly name: string; generate(request: AIRequest): Promise<AIResult>;
  // Optional, never required: providers that know their own model expose it for logging only.
  providerInfo?(): { provider?: string; model?: string | null; maxOutputTokens?: number };
}
export const intentResultSchema = z.strictObject({
  type: z.string(), target_id: z.string().nullable(),
  parameters_json: z.string().max(5000),
  clarification: z.string().nullable(),
});
export const narrativeResultSchema = narrativeSchema.omit({choice_offers:true}).extend({
  choices:providerEmptyArray(z.array(z.string().min(1).max(300)).max(6)),
  context_actions:providerEmptyArray(z.array(contextActionSchema).max(20)),
  mechanical_claims:providerEmptyArray(z.array(z.strictObject({kind:z.enum(['outcome','time','activity','position','inventory','relationship','evidence','injury','death','money','state','random','progress']),
    fact_index:z.number().int().min(0).max(11)})).max(12)).optional(),
  choice_semantics:providerEmptyArray(z.array(z.strictObject({index:z.number().int().min(0).max(5),intent_key:z.string().min(1).max(80),consequence_key:z.string().min(1).max(80),target_id:id.nullable()})).max(6)).optional(),
  item_claims:providerEmptyArray(z.array(z.strictObject({name:z.string().min(1).max(100),placement:z.enum(['held','inside_container','scene','incidental']),container_name:z.string().max(100).nullable(),position_label:z.string().max(100).nullable(),weight:z.number().min(0).max(50),container:z.boolean()})).max(12)),
  stable_locations:providerEmptyArray(z.array(z.strictObject({name:z.string().min(1).max(120),parent_id:id,travel_minutes:z.number().int().min(1).max(120),reenterable:z.boolean(),interactive:z.boolean()})).max(5)),
  interaction:z.strictObject({target_id:id,status:z.enum(['active','ended'])}).nullable().default(null), patches: providerEmptyArray(z.array(z.strictObject({
  op: z.literal('relationship_delta'), entity_id: id, target_id: id, dimension: id, delta: z.number().int().min(-2).max(2),
})).max(1)) });
// A bounded authoring blueprint is compiled into a fully validated World Package.
// No executable code or arbitrary modules can be generated by the initializer.
export const worldModuleIds = ['map','characters','relationships','inventory','commerce','attributes','aptitudes','skills','traits','equipment','quests','routine'] as const;
import { genderValues } from '../shared/gender.js';
import { AGE_MAX } from '../shared/age.js';

export const worldInitializationSchema = z.strictObject({
  id, title: z.string().min(1).max(120), description: z.string().max(2000),
  resolution_profile:z.enum(['classic_d20','bell_2d6','percentile_d100']).nullable().optional(),
  // Capability selection: a world only installs what its description actually needs.
  modules: z.array(z.enum(worldModuleIds)).min(1).max(12).default(['map','characters','relationships','inventory','commerce','routine']),

  currency: z.strictObject({ id, name: z.string().min(1).max(80) }),
  // Strict providers must answer every property, so optional data may arrive as `null`; null means absent.
  player: z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), gender: z.enum(genderValues).nullable().default(null), age: z.number().int().min(0).max(AGE_MAX).nullable().default(null), location_id: id.nullish(), cash: z.number().int().min(0).max(100000) }),
  locations: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), parent_id: id.nullable().default(null), kind: id.default('poi'), map_level: z.number().int().min(0).max(20).default(0), known_by_default: z.boolean().default(true) })).nullish(),
  routes: z.array(z.strictObject({ from: id, to: id, travel_minutes: z.number().int().min(1).max(120) })).nullish(),
  characters: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), gender: z.enum(genderValues).nullable().default(null), age: z.number().int().min(0).max(AGE_MAX).nullable().default(null), location_id: id.nullish(), role: z.string().max(100) })).min(1).max(5),
  items: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), weight: z.number().min(0).max(100), price: z.number().int().min(2).max(1000) })).nullish(),
  shop: z.strictObject({ id, name: z.string().min(1).max(120), location_id: id.nullish(), cash: z.number().int().min(100).max(100000) }).nullish(),

  hidden_notes: z.string().max(2000),
  hidden_truths: z.array(z.strictObject({
    id, commitment:z.enum(['HARD_TRUTH','SEEDED_TRUTH']), statement:z.string().min(1).max(2000), seed_constraint:z.string().max(500).nullable(),
    evidence:z.array(z.strictObject({id,description:z.string().min(1).max(1000),
      location_id:id.nullish(),anchor_entity_id:id.nullish(),scene_scope:z.string().max(120).nullish(),
      discoverability:z.strictObject({domain:id,difficulty:z.enum(['trivial','easy','normal','hard','very_hard','extreme'])}).nullish(),
    })).max(20),
  })).max(30).optional(),
  background_incidents:providerEmptyArray(z.array(backgroundIncidentSchema).max(3)).optional(),
  world_macro_arcs:providerEmptyArray(z.array(worldMacroArcSchema).max(2)).optional(),
  opening: z.string().max(2000),
});
