import { z } from 'zod';
import { id, narrativeSchema } from '../core/schema.js';
export type AIRole = 'world_initializer' | 'intent_interpreter' | 'narrator';
export interface AIRequest { role: AIRole; prompt: string; schema: unknown; threadId?: string; signal?: AbortSignal }
export interface AIResult { data: unknown; threadId?: string; recovered?: boolean }
export interface AIAdapter { readonly name: string; generate(request: AIRequest): Promise<AIResult> }
export const intentResultSchema = z.strictObject({
  type: z.string(), target_id: z.string().nullable(),
  parameters_json: z.string().max(5000),
  clarification: z.string().nullable(),
});
export const narrativeResultSchema = narrativeSchema.extend({ patches: z.array(z.strictObject({
  op: z.literal('relationship_delta'), entity_id: id, target_id: id, dimension: id, delta: z.number().int().min(-2).max(2),
})).max(1) });
// A bounded authoring blueprint is compiled into a fully validated World Package.
// No executable code or arbitrary modules can be generated by the initializer.
export const worldInitializationSchema = z.strictObject({
  id, title: z.string().min(1).max(120), description: z.string().max(2000),
  currency: z.strictObject({ id, name: z.string().min(1).max(80) }),
  player: z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), location_id: id, cash: z.number().int().min(0).max(100000) }),
  locations: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), parent_id: id.nullable().default(null), kind: id.default('poi'), map_level: z.number().int().min(0).max(20).default(0), known_by_default: z.boolean().default(true) })).min(4).max(16),
  routes: z.array(z.strictObject({ from: id, to: id, travel_minutes: z.number().int().min(1).max(120) })).min(2).max(20),
  characters: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), location_id: id, role: z.string().max(100) })).min(1).max(5),
  items: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), weight: z.number().min(0).max(100), price: z.number().int().min(2).max(1000) })).min(1).max(5),
  shop: z.strictObject({ id, name: z.string().min(1).max(120), location_id: id, cash: z.number().int().min(100).max(100000) }),
  hidden_notes: z.string().max(2000), opening: z.string().max(2000),
});
