import { z } from 'zod';
import { id, narrativeSchema } from '../core/schema.js';
export type AIRole = 'world_initializer' | 'intent_interpreter' | 'narrator' | 'gm_reasoning' | 'routine_compiler';
export interface AIRequest { role: AIRole; prompt: string; schema: unknown; threadId?: string; signal?: AbortSignal; maxOutputTokens?: number }
export interface AIResult { data: unknown; threadId?: string; recovered?: boolean; usage?: {input_tokens:number;output_tokens:number} }
export interface AIAdapter {
  readonly name: string; generate(request: AIRequest): Promise<AIResult>;
  // Optional, never required: providers that know their own model expose it for logging only.
  providerInfo?(): { provider?: string; model?: string | null };
}
export const intentResultSchema = z.strictObject({
  type: z.string(), target_id: z.string().nullable(),
  parameters_json: z.string().max(5000),
  clarification: z.string().nullable(),
});
export const narrativeResultSchema = narrativeSchema.extend({ interaction:z.strictObject({target_id:id,status:z.enum(['active','ended'])}).nullable().default(null), patches: z.array(z.strictObject({
  op: z.literal('relationship_delta'), entity_id: id, target_id: id, dimension: id, delta: z.number().int().min(-2).max(2),
})).max(1) });
// A bounded authoring blueprint is compiled into a fully validated World Package.
// No executable code or arbitrary modules can be generated by the initializer.
export const worldModuleIds = ['map','characters','relationships','inventory','commerce','attributes','aptitudes','skills','traits','equipment','quests','routine'] as const;
export const worldInitializationSchema = z.strictObject({
  id, title: z.string().min(1).max(120), description: z.string().max(2000),
  // Capability selection: a world only installs what its description actually needs.
  modules: z.array(z.enum(worldModuleIds)).min(1).max(12).default(['map','characters','relationships','inventory','commerce','routine']),

  currency: z.strictObject({ id, name: z.string().min(1).max(80) }),
  // Strict providers must answer every property, so optional data may arrive as `null`; null means absent.
  player: z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), location_id: id.nullish(), cash: z.number().int().min(0).max(100000) }),
  locations: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), parent_id: id.nullable().default(null), kind: id.default('poi'), map_level: z.number().int().min(0).max(20).default(0), known_by_default: z.boolean().default(true) })).nullish(),
  routes: z.array(z.strictObject({ from: id, to: id, travel_minutes: z.number().int().min(1).max(120) })).nullish(),
  characters: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), location_id: id.nullish(), role: z.string().max(100) })).min(1).max(5),
  items: z.array(z.strictObject({ id, name: z.string().min(1).max(120), description: z.string().max(1000), weight: z.number().min(0).max(100), price: z.number().int().min(2).max(1000) })).nullish(),
  shop: z.strictObject({ id, name: z.string().min(1).max(120), location_id: id.nullish(), cash: z.number().int().min(100).max(100000) }).nullish(),

  hidden_notes: z.string().max(2000), opening: z.string().max(2000),
});
