import {chromium,expect} from '@playwright/test';
import {once} from 'node:events';
import {mkdtemp,mkdir,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join,resolve} from 'node:path';
import {randomUUID} from 'node:crypto';
import {sparseSetup} from '../tests/sparse-fixture.js';
import {createApp} from '../src/server/app.js';
const root=await mkdtemp(join(tmpdir(),'agf-current-human-qa-')),shots=join(root,'screens');await mkdir(shots,{recursive:true});const fixture=await sparseSetup();
const save=await fixture.service.current(),player=save.entities.find(entity=>entity.id===save.player_state.entity_id)!;for(const npc of save.entities.filter(entity=>entity.type==='character'&&entity.id!==player.id))npc.components.location={location_id:String(player.components.location?.location_id)};save.last_turn={narrative:'广场上的人声与公告纸张的沙沙声交织在一起。',speaker:null,dialogue:null,choices:[],context_actions:[{target_id:'npc_lin',label:'问她在整理什么',intent:'向林舟询问她正在整理的公告',family:'communicate'},{target_id:'npc_lin',label:'保持距离观察',intent:'观察林舟的动作',family:'observe'}]};await fixture.service.storage.write(save);
const server=createApp(fixture.service,resolve('dist/client'),undefined,join(root,'assets')).listen(0,'127.0.0.1');await once(server,'listening');let browser:Awaited<ReturnType<typeof chromium.launch>>|null=null;
const id=randomUUID(),now=Date.now();
const task=(status:string)=>({id,game_id:save.game_id,extension_id:'qa_feature',original_request:'为人物增加一个可见的通用状态字段',normalized_requirements:['人物页显示独立状态'],requirement_history:['人物页显示独立状态'],complexity:'HIGH',status,workspace:join(root,'workspace'),current_version:'0.1.0',installed_version:status==='installed'?'0.1.0':null,revision:1,attempts:status==='developing'?2:3,budget:{max_attempts:6},milestones:[{id:'field',title:'人物独立状态',kind:'behavior',acceptance:['每个人物独立保存'],status:status==='installed'?'passed':'pending'},{id:'host',title:'人物页面显示',kind:'ui',acceptance:['真实人物详情可见'],status:status==='installed'?'passed':'pending'}],capability_gaps:status==='waiting_for_core_approval'?[{required_capability:'character.inline_editor',why_needed:'需要在人物页提供可编辑字段',affected_modules:['characters'],current_limitation:'当前只能展示',proposed_generic_capability:'通用人物字段编辑器',risk:'输入校验'}]:[],core_proposal:status==='waiting_for_core_approval'?{problem:'人物页还缺少通用文本编辑能力。',proposed_api:['人物字段编辑'],impact:['人物页面'],migration:'旧数据保持不变',tests:['人物页交互验证'],rollback:'停用新能力',risk:'需要验证输入',status:'pending'}:null,clarification_options:status==='waiting_for_user'?['每个人物独立保存','所有人物共用','你帮我决定']:[],clarification_rounds:status==='waiting_for_user'?1:0,artifacts:[],test_results:status==='failed'?[{version:'0.1.0',milestone:'core',passed:false,detail:'Coding backend failed: The operation was aborted'}]:[],history:[{at:new Date(now-261000).toISOString(),event:'created',detail:'开始开发'},{at:new Date(now-8000).toISOString(),event:'progress',detail:'完成上一阶段'}],message:status==='waiting_for_user'?'这个状态需要每个人物独立保存，还是所有人物共用？':status==='waiting_for_core_approval'?'当前功能需要补充人物页编辑能力。':status==='failed'?'自动重试与修复策略已用完，后台已经停止；候选没有安装。':status==='installed'?'版本已安装，可以继续提出修改要求。':'正在运行测试并检查人物页面。',candidate_job_id:status==='developing'?'job-2':null,preview:status==='installed'?{name:'人物状态',requirements:['人物页显示独立状态'],usage:'打开人物详情',rules:[],ui:['人物详情属性'],world_integration:'人物详情',canonical_writes:[],own_state:['状态：数值'],permissions:['扩展自有数据'],risk:'',version:'0.1.0',migration:[]}:null,started_at:new Date(now-261000).toISOString(),last_activity_at:new Date(now-8000).toISOString(),current_phase:status,active_job:status==='developing'?'正在运行测试':null,latest_progress_message:status==='developing'?'候选已生成，正在运行测试。':undefined,core_recovery:status==='failed'?{classification:'TRANSIENT_EXECUTION_FAILURE',attempts:3,max_attempts:3,replans:1,max_replans:1,providers_tried:['fixture'],last_error:'The operation was aborted'}:undefined});
let state='developing';
try{browser=await chromium.launch({headless:true,executablePath:process.env.BROWSER_EXECUTABLE??'C:/Program Files/Google/Chrome/Application/chrome.exe'});const base='http://127.0.0.1:'+(server.address() as any).port;const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));await page.route('**/api/development/tasks',route=>route.fulfill({contentType:'application/json',body:JSON.stringify([task(state)])}));
 await page.goto(base);await page.getByRole('button',{name:'继续当前世界',exact:true}).click();await page.screenshot({path:join(shots,'01-world-desktop.png'),fullPage:true});
 await page.getByText('林舟',{exact:true}).first().click();await page.screenshot({path:join(shots,'02-character-desktop.png'),fullPage:true});await page.getByRole('button',{name:'← 返回',exact:true}).click();await page.getByRole('button',{name:'查看操作',exact:true}).first().click();await page.getByRole('button',{name:'交流',exact:true}).click();await expect(page.getByRole('button',{name:'问她在整理什么',exact:true})).toBeVisible();await page.screenshot({path:join(shots,'03-affordance-desktop.png'),fullPage:true});
 await page.getByRole('button',{name:'系统',exact:true}).click();await page.locator('.system-advanced summary').click();await page.getByRole('button',{name:'打开开发工作区',exact:true}).click();await expect(page.locator('.system-advanced')).not.toHaveAttribute('open','');await page.getByLabel('开发任务').selectOption(id);await expect(page.locator('.development-status')).toContainText('正在开发');await page.screenshot({path:join(shots,'04-development-running.png'),fullPage:true});
 for(const [next,file,title] of [['waiting_for_user','05-development-waiting-user.png','需要你的回答'],['waiting_for_core_approval','06-development-waiting-approval.png','等待你的确认'],['failed','07-development-failed.png','开发失败'],['installed','08-development-completed.png','开发完成']] as const){state=next;await page.waitForTimeout(1400);await expect(page.locator('.development-status')).toContainText(title);await page.screenshot({path:join(shots,file),fullPage:true});}
 await page.locator('.task-organizer summary').click();await expect(page.getByRole('button',{name:/隐藏任务/})).toBeVisible();await expect(page.getByText('高级开发详情',{exact:true})).toBeVisible();await page.screenshot({path:join(shots,'09-task-organizer.png'),fullPage:true});
 const mobile=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true});const phone=await mobile.newPage();phone.on('pageerror',error=>errors.push(error.message));await phone.route('**/api/development/tasks',route=>route.fulfill({contentType:'application/json',body:JSON.stringify([task('installed')])}));await phone.goto(base);await phone.getByRole('button',{name:'继续当前世界',exact:true}).tap();await phone.screenshot({path:join(shots,'10-world-mobile.png'),fullPage:true});const nav=phone.getByRole('navigation',{name:'手机快捷导航'});await nav.getByRole('button',{name:'人物',exact:true}).tap();await phone.getByRole('button',{name:'林舟',exact:true}).last().tap();await phone.screenshot({path:join(shots,'11-character-mobile.png'),fullPage:true});await nav.getByRole('button',{name:'更多',exact:true}).tap();await phone.getByRole('region',{name:'更多面板'}).getByRole('button',{name:'系统',exact:true}).tap();await phone.locator('.system-advanced summary').tap();await phone.getByRole('button',{name:'打开开发工作区',exact:true}).tap();await expect(phone.locator('.system-advanced')).not.toHaveAttribute('open','');await phone.getByLabel('开发任务').selectOption(id);await expect(phone.locator('.development-status')).toContainText('开发完成');await phone.screenshot({path:join(shots,'12-development-mobile.png'),fullPage:true});
 const desktopOverflow=await page.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);const mobileOverflow=await phone.evaluate(()=>document.documentElement.scrollWidth-window.innerWidth);if(desktopOverflow>1||mobileOverflow>1)throw Error('Horizontal overflow: desktop='+desktopOverflow+', mobile='+mobileOverflow);
 if(errors.length)throw Error(errors.join('\n'));await writeFile(join(root,'results.json'),JSON.stringify({passed:true,screenshots:12,desktop:true,mobile:true},null,2));console.log('CURRENT HUMAN QA BROWSER PASS '+root);
}finally{if(browser)await browser.close();server.closeAllConnections();await new Promise<void>(done=>server.close(()=>done()));}
