import {chromium} from '@playwright/test';
import assert from 'node:assert/strict';import {once} from 'node:events';import {mkdir} from 'node:fs/promises';
import {sparseWorld,sparsePlan} from '../tests/sparse-fixture.js';import {GameService} from '../src/server/service.js';import {JsonStore} from '../src/storage/json-store.js';import {AIRuntime} from '../src/ai/runtime.js';import {createApp} from '../src/server/app.js';
const directory='.tmp/sparse-browser-'+Date.now();await mkdir(directory,{recursive:true});
let release:(()=>void)|undefined;
const service=new GameService(new JsonStore(directory),new AIRuntime({name:'delayed-compiler',generate:async()=>{await new Promise<void>(r=>release=r);return {data:sparsePlan}}}),sparseWorld());await service.newGame();await service.current();
const server=createApp(service).listen(0,'127.0.0.1');await once(server,'listening');const base='http://127.0.0.1:'+(server.address() as any).port;
let browser:Awaited<ReturnType<typeof chromium.launch>>|undefined;
try{browser=await chromium.launch({headless:true,...(process.env.BROWSER_EXECUTABLE?{executablePath:process.env.BROWSER_EXECUTABLE}:{})});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByRole('button',{name:'继续当前世界',exact:true}).click();await page.getByRole('button',{name:'生活模式',exact:true}).click();await page.getByLabel('生活规则',{exact:true}).fill('每天正常睡眠、上课、训练与固定兼职');await page.getByRole('button',{name:'开始生活模式',exact:true}).click();await page.getByText('后台模拟：运行中',{exact:true}).waitFor();
await page.getByRole('button',{name:'地图',exact:true}).click();await page.locator('.map-location-card').first().waitFor();await page.reload();await page.getByRole('button',{name:'继续当前世界',exact:true}).click();await page.getByRole('button',{name:'生活模式',exact:true}).click();await page.getByText('后台模拟：运行中',{exact:true}).waitFor();await page.screenshot({path:directory+'/running-after-refresh.png'});
await page.getByRole('button',{name:'请求安全暂停',exact:true}).click();assert(release);release();await page.getByText('后台模拟：已取消',{exact:true}).waitFor();assert.equal((await service.current()).runtime.time.minute,0);assert(!await page.locator('.message.error').count());assert.deepEqual(errors,[]);await page.screenshot({path:directory+'/cancelled.png'});console.log('SPARSE BROWSER PASS: short job request, browse map while AI waits, refresh reconnect, benign cancellation, unchanged time. '+directory);
}finally{release?.();for(let i=0;i<200&&service.routineLease;i++)await new Promise(r=>setTimeout(r,10));await browser?.close();await new Promise<void>(r=>server.close(()=>r()));}
