import {isEmptyWorld} from '../shared/world-intent.js';
import {focusPanelEntity} from './entity-focus.js';
import {ExtensionPanel,type ExtensionIntent} from './ExtensionPanel.js';
import {SystemPanel} from './SystemPanel.js';
import {WorldLauncher} from './WorldLauncher.js';
import type {AgentResult} from '../agent/contracts.js';
import {shouldAutoRetry} from './retry-policy.js';

import {displayDiagnostic} from '../shared/display.js';
import type {RoutineJob} from '../routine/jobs.js';
import { useEffect, useRef, useState } from 'react';
import type { ActionInput, ContextActionSuggestion, Entity, PublicView } from '../shared/contracts.js';
import { request, session, uploadAvatar as uploadAvatarFile, uploadVisualAsset as uploadVisualAssetFile } from './api.js';
import { Avatar, CharacterDetail, locationOf, nameOf, panelRegistry } from './panels.js';
import type {AvatarCropMetadata} from '../shared/avatar.js';
import { avatarFromFullbody } from './avatar-crop.js';

type PromptProfile = { id:string;version:string;engine_policy:string;world_initializer:string;intent_interpreter:string;narrator:string;npc_decision:string;gm_reasoning:string };
type ProviderDescriptor = { id:string;label:string;note:string;requires_api_key:boolean;supports_base_url:boolean;default_model?:string };
type ProviderInfo = { provider:string;name?:string;model?:string|null;base_url?:string|null;api_key_configured?:boolean;persisted?:boolean;saved_provider?:string|null };
type ProviderResponse = { current:ProviderInfo|null;providers:ProviderDescriptor[] };
function isPromptProfile(value: unknown): value is PromptProfile { if(!value||typeof value!=='object')return false;const x=value as Record<string,unknown>;return ['id','version','engine_policy','world_initializer','intent_interpreter','narrator','npc_decision','gm_reasoning'].every(k=>typeof x[k]==='string'); }

function sceneSummary(raw: unknown) {
  const text=String(raw??'').trim(); if(!text)return '';
  if(text.startsWith('{')) try { const value=JSON.parse(text) as Record<string,unknown>; const parts:string[]=[]; if(typeof value.role==='string')parts.push(value.role); if(typeof value.current_relationship==='string')parts.push(value.current_relationship); if(Array.isArray(value.known_state))parts.push(...value.known_state.filter(x=>typeof x==='string').slice(0,2) as string[]); if(parts.length)return parts.join(' · ').slice(0,220); } catch {}
  return text.length>220?`${text.slice(0,219)}…`:text;
}

function SceneContext({ view, busy, onContextAction, onSuggestedAction, onSelectEntity }:{view:PublicView;busy:boolean;onContextAction:(action:string,target:Entity)=>void;onSuggestedAction:(suggestion:ContextActionSuggestion,target:Entity)=>void;onSelectEntity?:(entity:Entity)=>void}) {
  const current=locationOf(view), [expanded,setExpanded]=useState<string|null>(null);
  const entities=view.entities.filter(e=>e.id!==view.player_id&&e.components.location?.location_id===current&&e.components.identity);
  const suggestions=view.last_turn?.context_actions??[];
  useEffect(()=>{ if(expanded && !entities.some(e=>e.id===expanded)) setExpanded(null); },[current,expanded,entities.length]);
  if(!entities.length)return <section className="scene-context"><div className="context-title"><span>当前场景</span><small>没有已登记的关键人物或物体</small></div></section>;
  return <section className="scene-context"><div className="context-title"><span>当前场景</span><small>{entities.length} 个可关注对象</small></div><div className="context-list">{entities.map(entity=>{
    const actions=view.actions.filter(a=>a.visibility==='contextual'&&!!a.target_component&&!!entity.components[a.target_component]);
    const contextual=suggestions.filter(x=>x.target_id===entity.id);
    const open=expanded===entity.id;
    const description=sceneSummary(entity.components.identity?.description);
    return <article className={`context-entity ${open?'expanded':''}`} key={entity.id}><div className="context-summary"><div className="context-identity">{Boolean(entity.components.identity?.avatar_id)&&<button type="button" className="context-avatar-button" title={entity.components.character?`查看 ${nameOf(entity)} 详情`:nameOf(entity)} onClick={()=>entity.components.character&&onSelectEntity?.(entity)}><Avatar entity={entity}/></button>}<div>{entity.components.character?<button type="button" className="name-link" onClick={()=>onSelectEntity?.(entity)}><strong>{nameOf(entity)}</strong></button>:<strong>{nameOf(entity)}</strong>}<small>{entity.components.character?'人物':entity.components.shop?'商店':entity.type}</small></div></div><button type="button" className="quiet" disabled={busy} onClick={()=>setExpanded(open?null:entity.id)}>{open?'收起':'查看操作'}</button></div>{open&&<div className="context-detail">{description&&<p>{description}</p>}<div className="context-actions">{actions.map(a=><button type="button" key={`hard:${a.type}`} className="quiet" disabled={busy} onClick={()=>onContextAction(a.type,entity)}>{a.label}</button>)}{contextual.map((x,i)=><button type="button" key={`suggest:${i}:${x.label}`} className="quiet suggested-action" disabled={busy} onClick={()=>onSuggestedAction(x,entity)}>{x.label}</button>)}{!actions.length&&!contextual.length&&<small>当前没有场景建议；你仍可在下方自由描述行动。</small>}</div></div>}</article>;
  })}</div></section>;
}

export function App() {
  const [view,setView]=useState<PublicView|null>(null),[engine,setEngine]=useState(''),[ready,setReady]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[messageKind,setMessageKind]=useState<'success'|'info'|'error'>('info');
  const [extensionIntent,setExtensionIntent]=useState<ExtensionIntent|null>(null);
  const [mobilePage,setMobilePage]=useState<'game'|'panel'|'more'>('game');
  const [cropTarget,setCropTarget]=useState<string|null>(null);
  const [mediaBusy,setMediaBusy]=useState(false);
  const [routineJob,setRoutineJob]=useState<RoutineJob|null>(null),[agentReply,setAgentReply]=useState<{intent:string;message:string}|null>(null);
  const routineAuto=!!routineJob&&['queued','running'].includes(routineJob.status);
  const [tab,setTab]=useState('status'),[input,setInput]=useState(''),[description,setDescription]=useState(''),[entered,setEntered]=useState(false);
  const [promptText,setPromptText]=useState(''),[promptProfile,setPromptProfile]=useState<PromptProfile|null>(null),[promptName,setPromptName]=useState('');
  const [providers,setProviders]=useState<ProviderResponse|null>(null),[providerOpen,setProviderOpen]=useState(false),[providerId,setProviderId]=useState('codex'),[providerKey,setProviderKey]=useState(''),[providerModel,setProviderModel]=useState(''),[providerBase,setProviderBase]=useState(''),[providerPersist,setProviderPersist]=useState(true);
  const [composeTarget,setComposeTarget]=useState<Entity|null>(null),[composeAction,setComposeAction]=useState<string|null>(null),[composeLabel,setComposeLabel]=useState(''),[listening,setListening]=useState(false),[selectedCharacterId,setSelectedCharacterId]=useState<string|null>(null);
  const jsonRef=useRef<HTMLInputElement>(null),promptRef=useRef<HTMLInputElement>(null),actionRef=useRef<HTMLTextAreaElement>(null),sidebarScrollRef=useRef<HTMLDivElement>(null),storyRef=useRef<HTMLElement>(null),sidebarRef=useRef<HTMLElement>(null),pending=useRef<{path:'action'|'input';body:unknown}|null>(null),recognitionRef=useRef<{stop:()=>void}|null>(null);

  const [systemHandoff,setSystemHandoff]=useState<{input:string;result:any}|null>(null);
  const [entityFocus,setEntityFocus]=useState<string|null>(null);
  const requestSequence=useRef(0),operationBusy=useRef(false),autoRetried=useRef(false);
  useEffect(()=>{
    if(!entityFocus)return;
    let card:HTMLElement|null=null,frame=0,tries=0;
    const focus=()=>{card=focusPanelEntity(sidebarRef.current,entityFocus);if(!card&&++tries<4)frame=requestAnimationFrame(focus);};
    frame=requestAnimationFrame(focus);
    return()=>{cancelAnimationFrame(frame);card?.classList.remove('entity-highlight');};
  },[entityFocus,tab,view?.game_id]);

  function clearMessage(){setMessage('');setMessageKind('info');}
  function showMessage(text:string,kind:'success'|'info'|'error'='success'){if(!text)return;const readable=displayDiagnostic(text,view?.entities??[],view?.locations??[]);if(readable.length>90&&kind!=='error'){setAgentReply({intent:'RESPONSE',message:readable});return;}setMessage(readable);setMessageKind(kind);}

  function syncProviderForm(p:ProviderResponse){setProviders(p);const current=p.current;if(current){setEngine(current.provider);setProviderId(current.provider);setProviderModel(current.model??'');setProviderBase(current.base_url??'');setProviderPersist(Boolean(current.persisted || !current.saved_provider));}}
  useEffect(()=>{void(async()=>{try{const s=await session();setEngine(s.engine);const p=await request<ProviderResponse>('ai/providers');syncProviderForm(p);setView(await request<PublicView|null>('state'));setReady(true);}catch(e){showMessage(String(e),'error');}})();},[]);
  useEffect(()=>{if(!message||messageKind==='error')return;const timer=window.setTimeout(()=>clearMessage(),3500);return()=>window.clearTimeout(timer);},[message,messageKind]);
  useEffect(()=>{if(!ready)return;const sync=()=>void request<ProviderResponse>('ai/providers').then(p=>{setProviders(p);if(p.current){setEngine(p.current.provider);if(!providerOpen){setProviderId(p.current.provider);setProviderModel(p.current.model??'');setProviderBase(p.current.base_url??'');setProviderPersist(p.current.persisted??true);}}}).catch(()=>undefined);const timer=window.setInterval(sync,10000);const onFocus=()=>sync();const onVisibility=()=>{if(document.visibilityState==='visible')sync()};window.addEventListener('focus',onFocus);document.addEventListener('visibilitychange',onVisibility);return()=>{window.clearInterval(timer);window.removeEventListener('focus',onFocus);document.removeEventListener('visibilitychange',onVisibility)};},[ready,providerOpen]);
  const engineLabel=engine==='deepseek'?'DeepSeek':engine==='codex'?'Codex':engine==='openai'?'OpenAI API':engine==='responses-compatible'?'兼容 API':engine==='mock'?'离线 Mock':engine||'AI';
  async function operate(path:string,body:unknown={},enterWorld=true){if(operationBusy.current)return;operationBusy.current=true;const sequence=++requestSequence.current;setEntityFocus(null);setBusy(true);clearMessage();setAgentReply(null);try{let next:PublicView|RoutineJob|ExtensionIntent|AgentResult;try{next=await request<PublicView|RoutineJob|ExtensionIntent|AgentResult>(path,body);}catch(firstError){const policy=(firstError as {payload?:{retry_policy?:string}}).payload?.retry_policy;if(!shouldAutoRetry(policy,autoRetried.current))throw firstError;autoRetried.current=true;try{const latest=await request<PublicView>('state');if(sequence===requestSequence.current)setView(latest);const raw=(body&&typeof body==='object'?body:{}) as Record<string,unknown>;next=await request<PublicView|RoutineJob|ExtensionIntent|AgentResult>(path,{...raw,request_id:requestId(),game_id:latest.game_id,expected_revision:latest.revision});}finally{autoRetried.current=false;}}if(sequence!==requestSequence.current)return;if('ui_actions' in next){if('system_handoff' in next)setSystemHandoff((next as any).system_handoff);if(next.view)setView(next.view);setAgentReply(next.presentation==='story'?null:{intent:next.intent,message:next.message});for(const action of next.ui_actions){if(action.kind==='open_panel')selectTab(action.panel);if((action.kind==='open_character_detail')&&'entity_id' in action){const target=(next.view??view)?.entities.find(entity=>entity.id===action.entity_id);if(target)openCharacter(target);}if(action.kind==='export_save')void exportFile();}const focus=next.ui_actions.find(a=>a.kind==='focus_entity');setEntityFocus(focus&&'entity_id' in focus?focus.entity_id:null);pending.current=null;return;}if('kind' in next){setExtensionIntent(next);setTab('extensions');setMobilePage('panel');pending.current=null;return;}if('job_id' in next){setRoutineJob(next);setTab('routine');pending.current=null;return;}let latest=next;if(['action','input'].includes(path)){try{latest=await request<PublicView>('state')}catch{/* action response is still authoritative enough for display */}}setView(latest);const note=latest.notices.join(' ');if(note)showMessage(note,'success');pending.current=null;if(enterWorld)setEntered(true);if(['new','import','load'].includes(path)){const isRoutine=String((body as {action?:{type?:string}})?.action?.type??'').includes('ROUTINE');setTab(isRoutine?'routine':'status');setSelectedCharacterId(null);requestAnimationFrame(()=>sidebarScrollRef.current?.scrollTo({top:0,behavior:'smooth'}));}}catch(e){const text=(e as Error).message;if(/状态已更新|revision|版本.*更新/i.test(text)){try{const latest=await request<PublicView>('state');setView(latest);showMessage('状态已自动同步到最新版本。原请求没有自动重放，避免重复执行；需要时可点击“重试原请求”。','error');}catch{showMessage(text,'error')}}else showMessage(text,'error');}finally{operationBusy.current=false;setBusy(false)}}
  async function retryPending(){if(!pending.current||!view||busy)return;const original=pending.current;const raw=(original.body&&typeof original.body==='object'?original.body:{}) as Record<string,unknown>;const body={...raw,request_id:raw.request_id??requestId(),game_id:view.game_id,expected_revision:view.revision};pending.current={path:original.path,body};await operate(original.path,body);}
  function requestId(){
    const c=globalThis.crypto as Crypto|undefined;
    if(c?.randomUUID)return c.randomUUID();
    const bytes=new Uint8Array(16);
    if(c?.getRandomValues)c.getRandomValues(bytes); else for(let i=0;i<16;i++)bytes[i]=Math.floor(Math.random()*256);
    bytes[6]=(bytes[6]&0x0f)|0x40;bytes[8]=(bytes[8]&0x3f)|0x80;
    const hex=Array.from(bytes,b=>b.toString(16).padStart(2,'0')).join('');
    return `${hex.slice(0,8)}-${hex.slice(8,12)}-${hex.slice(12,16)}-${hex.slice(16,20)}-${hex.slice(20)}`;
  }
  async function act(action?:ActionInput,text?:string){
    if(!view||busy)return;
    if(action&&['START_ROUTINE','CONTINUE_ROUTINE'].includes(action.type)){
      try{const job=await request<RoutineJob>('routine/run',{request_id:requestId(),game_id:view.game_id,expected_revision:view.revision,action});setRoutineJob(job);setTab('routine');clearMessage();}catch(e){showMessage((e as Error).message,'error');}return;
    }
    try{
      const path:'action'|'input'=action?'action':'input';
      const body={request_id:requestId(),game_id:view.game_id,expected_revision:view.revision,...(action?{action}:{input:text})};
      pending.current={path,body};
      await operate(path,body);
      setInput('');setComposeTarget(null);setComposeAction(null);setComposeLabel('');
    }catch(e){showMessage(e instanceof Error?e.message:String(e),'error');}
  }
  useEffect(()=>{
    if(!ready)return;let disposed=false,inFlight=false;
    const poll=async()=>{if(inFlight)return;inFlight=true;try{const job=await request<RoutineJob|null>('routine/jobs');if(disposed)return;setRoutineJob(job);if(job){const next=await request<PublicView>('state');if(!disposed)setView(next);}}catch{/* Reconnect on the next short poll; never cancel server work on tab change. */}finally{inFlight=false;}};
    void poll();const timer=window.setInterval(()=>void poll(),1200);return()=>{disposed=true;window.clearInterval(timer);};
  },[ready]);
  async function pauseRoutine(){if(!routineJob)return;try{setRoutineJob(await request<RoutineJob>('routine/jobs/'+routineJob.job_id+'/cancel',{}));showMessage('已请求暂停，将在当前安全结算点停止。','info');}catch(e){showMessage((e as Error).message,'error');}}
  async function exportFile(){setBusy(true);clearMessage();try{const save=await request('export',{}),url=URL.createObjectURL(new Blob([JSON.stringify(save,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='agent-game-save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);showMessage('存档已导出，包含完整世界与 GM 数据。','success');}catch(e){showMessage((e as Error).message,'error')}finally{setBusy(false)}}
  async function loadJson(file:File){if(file.size>2*1024*1024)throw new Error('JSON 不能超过 2 MB');await operate('import',JSON.parse(await file.text()));}
  async function loadPrompt(file:File){if(file.size>512*1024)throw new Error('Prompt 文件不能超过 512 KB');const raw=await file.text();try{const parsed=JSON.parse(raw) as unknown;if(isPromptProfile(parsed)){setPromptProfile(parsed);setPromptText('');setPromptName(file.name);showMessage(`已载入 Prompt Profile：${parsed.id} / ${parsed.version}`,'success');return;}}catch{}setPromptText(raw);setPromptProfile(null);setPromptName(file.name);showMessage(`已载入提示词：${file.name}`,'success');}
  async function createWorld(){if(!description.trim())return;const body:Record<string,unknown>={description:description.trim()};if(promptProfile)body.prompt_profile=promptProfile;else if(promptText.trim())body.prompt_text=promptText;await operate('new',body);}
  function chooseContextAction(action:string,target:Entity){setComposeAction(action);setComposeTarget(target);setComposeLabel(view?.actions.find(a=>a.type===action)?.label??action);setInput('');const meta=view?.actions.find(a=>a.type===action);if(meta?.requires_text)setTimeout(()=>actionRef.current?.focus(),0);}
  function chooseSuggestedAction(suggestion:ContextActionSuggestion,target:Entity){setComposeAction('SOCIAL_INTERACT');setComposeTarget(target);setComposeLabel(suggestion.label);setInput(suggestion.intent);setTimeout(()=>actionRef.current?.focus(),0);}
  async function uploadAvatar(entity:Entity,file:File,crop?:AvatarCropMetadata){if(!view||mediaBusy)return;setMediaBusy(true);clearMessage();try{const next=await uploadAvatarFile(entity.id,file,view.game_id,view.revision,crop);setView(next);showMessage(`已更新 ${nameOf(entity)} 的头像。图片保存在本机 data/assets/avatars，不调用 AI。`,'success');}catch(e){showMessage((e as Error).message,'error');throw e;}finally{setMediaBusy(false)}}
  async function clearAvatar(entity:Entity){if(!view||mediaBusy||!entity.components.identity?.avatar_id)return;if(!window.confirm(`移除 ${nameOf(entity)} 的头像并恢复为空白？\n\n全身图不会被删除。`))return;setMediaBusy(true);clearMessage();try{const next=await request<PublicView>(`avatar/${entity.id}/clear`,{game_id:view.game_id,expected_revision:view.revision});setView(next);showMessage(`已移除 ${nameOf(entity)} 的头像。`,'success');}catch(e){showMessage((e as Error).message,'error')}finally{setMediaBusy(false)}}
  async function uploadVisualAsset(entity:Entity,slot:string,file:File){if(!view||mediaBusy)return;setMediaBusy(true);clearMessage();try{const hadAvatar=Boolean(entity.components.identity?.avatar_id);let next=await uploadVisualAssetFile(entity.id,slot,file,view.game_id,view.revision);let autoAvatar=false;if(slot==='fullbody'&&!hadAvatar){try{const cropped=await avatarFromFullbody(file);next=await uploadAvatarFile(entity.id,cropped,next.game_id,next.revision);autoAvatar=true;}catch{/* fullbody upload succeeded; user can still upload a dedicated avatar manually */}}setView(next);showMessage(autoAvatar?`已更新 ${nameOf(entity)} 的全身图，并从图像上部中央自动生成头像；不满意时可以单独更换头像。`:`已更新 ${nameOf(entity)} 的${slot==='fullbody'?'全身图':'人物图片'}。图片仅保存在本机 data/assets/visuals，不调用 AI。`,'success');}catch(e){showMessage((e as Error).message,'error')}finally{setMediaBusy(false)}}
  function openCharacter(entity:Entity,forCrop=false){setCropTarget(forCrop?entity.id:null);setMobilePage('panel');setSelectedCharacterId(entity.id);requestAnimationFrame(()=>{sidebarScrollRef.current?.scrollTo({top:0,behavior:'smooth'});if(window.matchMedia('(max-width: 850px)').matches)sidebarRef.current?.scrollIntoView({behavior:'smooth',block:'start'});});}
  function selectTab(next:string){setEntityFocus(null);setMobilePage('panel');setSelectedCharacterId(null);setTab(next);requestAnimationFrame(()=>sidebarScrollRef.current?.scrollTo({top:0,behavior:'smooth'}));}
  async function importCharacterCard(file:File){if(!view||busy)return;if(file.size>2*1024*1024){showMessage('角色卡 JSON 不能超过 2 MB。','error');return;}let card:unknown;try{card=JSON.parse(await file.text())}catch{showMessage('角色卡不是有效 JSON。','error');return;}const root=card&&typeof card==='object'?card as Record<string,unknown>:{};const data=root.data&&typeof root.data==='object'?root.data as Record<string,unknown>:root;const label=typeof data.name==='string'&&data.name.trim()?data.name.trim():'这个角色';if(!window.confirm(`把「${label}」导入当前世界并放到玩家当前位置？

这不会推进游戏时间，也不会调用 AI。`))return;setBusy(true);clearMessage();try{const next=await request<PublicView>('character-card/import',{game_id:view.game_id,expected_revision:view.revision,card});setView(next);showMessage(next.notices.join(' ')||`已导入 ${label}。`,'success');setTab('characters');requestAnimationFrame(()=>sidebarRef.current?.scrollIntoView({behavior:'smooth',block:'start'}));}catch(e){showMessage((e as Error).message,'error')}finally{setBusy(false)}}
  function startVoice(){
    type RecognitionErrorEvent={error?:string};
    type RecognitionCtor = new()=>{lang:string;interimResults:boolean;continuous:boolean;start:()=>void;stop:()=>void;onresult:((e:{results:ArrayLike<{0:{transcript:string};isFinal:boolean}>})=>void)|null;onend:(()=>void)|null;onerror:((e:RecognitionErrorEvent)=>void)|null};
    const lanHttp=window.location.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(window.location.hostname);
    if(lanHttp||!window.isSecureContext){
      actionRef.current?.focus();
      showMessage('手机当前通过局域网 HTTP 访问。Chrome 会禁止网页语音识别/麦克风权限；请先用手机键盘自带的语音输入。网页语音按钮需要 HTTPS 后才能正常工作。','error');
      return;
    }
    const w=window as unknown as {SpeechRecognition?:RecognitionCtor;webkitSpeechRecognition?:RecognitionCtor};const Ctor=w.SpeechRecognition??w.webkitSpeechRecognition;
    if(!Ctor){actionRef.current?.focus();showMessage('当前浏览器没有提供网页语音识别。可以先使用手机键盘自带的麦克风输入。','error');return;}
    if(listening){recognitionRef.current?.stop();return;}
    const r=new Ctor();r.lang='zh-CN';r.interimResults=false;r.continuous=false;r.onresult=e=>{const text=Array.from(e.results).map(x=>x[0].transcript).join('');setInput(v=>(v&& !v.endsWith(' ')?v+' ':'')+text);};r.onend=()=>setListening(false);r.onerror=e=>{setListening(false);const denied=e?.error==='not-allowed'||e?.error==='service-not-allowed';showMessage(denied?'浏览器没有授予语音识别权限。请检查站点麦克风权限，或使用手机键盘语音输入。':'语音识别没有完成，请重试或继续打字。','error');};recognitionRef.current=r;setListening(true);try{r.start()}catch(e){setListening(false);showMessage(e instanceof Error?e.message:'语音识别启动失败。','error');}
  }
  async function applyProvider(){setBusy(true);clearMessage();try{const body:Record<string,unknown>={provider:providerId,persist:providerPersist};if(providerKey.trim())body.api_key=providerKey.trim();if(providerModel.trim())body.model=providerModel.trim();if(providerBase.trim())body.base_url=providerBase.trim();const info=await request<ProviderInfo>('ai/provider',body);setProviderKey('');const p=await request<ProviderResponse>('ai/providers');syncProviderForm(p);setProviderOpen(false);showMessage(`AI 已切换为 ${p.providers.find(x=>x.id===info.provider)?.label??info.provider}${info.persisted?'，并保存在这台电脑。':'，仅用于当前服务进程。'}`,'success');}catch(e){showMessage((e as Error).message,'error')}finally{setBusy(false)}}
  async function forgetProvider(){setBusy(true);clearMessage();try{await request<ProviderInfo>('ai/provider/forget',{});const p=await request<ProviderResponse>('ai/providers');syncProviderForm(p);showMessage('已删除本机保存的 AI Provider 配置；当前进程仍可继续使用，重启后将回到环境变量或默认设置。','success');}catch(e){showMessage((e as Error).message,'error')}finally{setBusy(false)}}
  const panels=view?.panels??[],mobilePrimary=panels.filter(p=>(p.mobile_group??'secondary')==='primary'&&panelRegistry[p.id]).slice(0,4),ActivePanel=panelRegistry[tab],location=view?.locations.find(l=>l.id===locationOf(view)),selectedProvider=providers?.providers.find(p=>p.id===providerId),selectedCharacter=view?.entities.find(e=>e.id===selectedCharacterId&&!!e.components.character),speaker=view?.last_turn?.speaker?view.entities.find(e=>e.id===view.last_turn?.speaker):undefined;
  return <div className="shell">
    <header className="topbar compact-topbar"><button className="brand brand-button icon-brand" title="返回启动页" aria-label="返回启动页" onClick={()=>setEntered(false)}><span className="brand-mark">A</span></button><div className="header-right"><button className="engine engine-button" onClick={()=>setProviderOpen(true)}>{engineLabel} ▾</button><span className="version">v0.1.16</span></div></header>
    <main className={entered&&view?'play-main mobile-page-'+mobilePage:''}>
      {message&&<div role="alert" className={`notice-toast ${messageKind}`}><div className="notice-line"><span>{message}</span><button type="button" className="notice-close" aria-label="关闭提示" onClick={clearMessage}>×</button></div>{pending.current&&messageKind==='error'&&<div className="button-row compact"><button disabled={busy} onClick={()=>void retryPending()}>重试原请求</button><button disabled={busy} onClick={()=>void request<PublicView>('state').then(next=>{setView(next);showMessage('已刷新到最新状态。','info')})}>刷新状态</button></div>}</div>}
      {!ready?<section className="welcome"><h1>连接本地框架…</h1><p>请确认游戏服务已启动。</p></section>:!entered?<section className="launcher"><div className="launcher-heading"><span className="eyebrow">BLANK WORKSPACE</span><h1>载入、创建，或继续一个世界。</h1><p>世界、Prompt 与 AI Provider 相互独立。你可以用 Codex 会员模式，也可以切换 API。</p></div><div className="launcher-grid">
        {view&&<article className="launch-card continue-card"><small>当前自动存档</small><h2>{view.title}</h2><p>{view.description}</p><div className="launch-meta"><span>{view.locations.find(l=>l.id===locationOf(view))?.name}</span><span>第 {view.revision} 回合</span></div><button disabled={busy} onClick={()=>setEntered(true)}>继续当前世界</button></article>}
        <article className="launch-card create-card"><small>AI WORLD</small><h2>创建新世界</h2><WorldLauncher busy={busy} onCreated={created=>{setView(created);setEntered(true);setTab('status');}} onCustom={text=>void operate('new',{description:text})}/><label htmlFor="world">
告诉 AI 你想进入怎样的世界</label><textarea id="world" value={description} onChange={e=>setDescription(e.target.value)} maxLength={12000} placeholder="例如：现代城市背景，以社会关系、学习和职业为核心。玩家刚刚搬入一座陌生城市。"/><div className="prompt-slot"><div><strong>{promptName?'已载入 Prompt':'可选：导入 Prompt'}</strong><small>{promptName||'支持 .txt / .md / Prompt Profile .json；它会随新世界保存。'}</small></div><div className="button-row compact"><button type="button" className="quiet" onClick={()=>promptRef.current?.click()}>导入提示词</button>{promptName&&<button type="button" className="quiet" onClick={()=>{setPromptName('');setPromptText('');setPromptProfile(null)}}>移除</button>}</div></div><button disabled={busy||(engine==='mock'&&!isEmptyWorld(description))||!description.trim()} onClick={()=>void createWorld()}>{busy?'正在构建世界…':'创建世界'}</button></article>
        <article className="launch-card"><small>IMPORT</small><h2>导入 JSON</h2><p>载入标准 Save Package 或 World Package，由 Framework 校验后成为当前世界。</p><button className="quiet" disabled={busy} onClick={()=>jsonRef.current?.click()}>选择 JSON 文件</button><small>旧版非标准存档仍需先转换；不会静默改写正史。</small></article>
        <article className="launch-card provider-card"><small>AI PROVIDER</small><h2>{engineLabel}</h2><p>{providers?.providers.find(p=>p.id===providers.current?.provider)?.note??'选择游戏运行时使用的模型来源。'}</p><button className="quiet" onClick={()=>setProviderOpen(true)}>切换模型 / API</button></article>
      </div></section>:view?<><div className="game-layout"><section ref={storyRef} className="story-column"><div className="scene-heading"><span className="eyebrow">当前位置</span><h2>{String(view.entities.find(e=>e.id===view.player_id)?.components.scene_position?.label??location?.name??'当前场景')}</h2><p>{location?.description}</p></div><article className="story"><div className="story-label">此刻的故事 <button className="quiet" disabled={busy||!view.can_undo} onClick={()=>{if(window.confirm('将恢复到上一回合执行前的世界状态。'))void operate('undo',{request_id:requestId(),game_id:view.game_id,expected_revision:view.revision});}}>↶ 撤回上一步</button><span>{busy?'处理中…':'已自动保存'}</span></div><p className="narrative">{view.last_turn?.narrative||view.description}</p>
{view.last_turn?.dialogue&&<div className="dialogue-card"><button type="button" className="dialogue-speaker" disabled={!speaker} onClick={()=>speaker&&openCharacter(speaker)}>{speaker?<Avatar entity={speaker}/>:<span className="avatar">？</span>}<span><strong>{nameOf(speaker)}</strong>{!speaker&&<small>说话者未登记</small>}</span></button><p>{view.last_turn.dialogue}</p></div>}</article>{agentReply&&<div className="agent-reply" role="status"><div className="agent-reply-head"><small>游戏助手</small><button type="button" className="notice-close" aria-label="关闭回复" onClick={()=>setAgentReply(null)}>×</button></div><p>{agentReply.message}</p></div>}
        <SceneContext view={view} busy={busy} onContextAction={chooseContextAction} onSuggestedAction={chooseSuggestedAction} onSelectEntity={openCharacter}/>
        <form className="action-box" onSubmit={e=>{e.preventDefault();const meta=composeAction?view.actions.find(a=>a.type===composeAction):undefined;if(composeAction&&composeTarget){if(meta?.requires_text&&!input.trim())return;const parameters:Record<string,unknown>={};if(meta?.requires_text)parameters[meta.text_parameter??'text']=input.trim();void act({type:composeAction,target_id:composeTarget.id,parameters});return;}if(!input.trim())return;void act(undefined,input)}}><div className="composer-head"><label htmlFor="action">{composeAction&&composeTarget?`待执行：${composeLabel || (view.actions.find(a=>a.type===composeAction)?.label ?? composeAction)} · ${nameOf(composeTarget)}`:'你想做什么，或想知道什么？'}</label>{composeTarget&&<button type="button" className="text-button" onClick={()=>{setComposeTarget(null);setComposeAction(null);setComposeLabel('');setInput('')}}>取消当前动作</button>}</div><textarea ref={actionRef} id="action" value={input} onChange={e=>setInput(e.target.value)} maxLength={2000} placeholder={composeAction&&view.actions.find(a=>a.type===composeAction)?.requires_text?'补充这次行动的具体内容。':'可以描述角色行动，也可以直接问问题。例如：去找一位熟人；我和某个人现在是什么关系。'} disabled={busy}/><div className="action-footer"><span>{composeAction?'已选择动作；点击确认后才会真正执行':''}</span><div className="composer-buttons"><button type="button" className={`voice-button ${listening?'listening':''}`} disabled={busy} onClick={startVoice}>{listening?'停止语音':'🎙 语音'}</button><button disabled={busy||(composeAction?!!view.actions.find(a=>a.type===composeAction)?.requires_text&&!input.trim():!input.trim())}>{busy?'请稍候…':composeAction?'确认并执行 →':'发送 →'}</button></div></div></form>
      </section><aside ref={sidebarRef} className="sidebar"><nav aria-label="世界面板">{panels.filter(p=>panelRegistry[p.id]).map(p=><button key={p.id} className={tab===p.id?'active':''} onClick={()=>selectTab(p.id)}>{p.label}</button>)}</nav><div ref={sidebarScrollRef} className="sidebar-scroll"><section className={`panel ${selectedCharacter?'character-detail-panel':''}`}>{selectedCharacter?<CharacterDetail key={selectedCharacter.id+String(cropTarget)} initialCropOpen={cropTarget===selectedCharacter.id} view={view} entity={selectedCharacter} busy={busy} act={a=>void act(a)} uploadAvatar={uploadAvatar} clearAvatar={clearAvatar} uploadVisualAsset={uploadVisualAsset} importCharacterCard={importCharacterCard} onClose={()=>setSelectedCharacterId(null)}/>:<><h2>{tab==='system'?'系统':tab==='saves'?'管理存档':panels.find(p=>p.id===tab)?.label}</h2>{tab==='extensions'?<ExtensionPanel view={view} intent={extensionIntent} onView={setView}/>:tab==='system'?<SystemPanel handoff={systemHandoff} view={view} onView={setView} onOpenLogs={()=>selectTab('logs')} onExport={()=>void exportFile()} onOpenCharacterCrop={(id:string)=>{const target=view.entities.find(entity=>entity.id===id);if(target)openCharacter(target,true);}}
 busy={busy} act={()=>{}}/>:tab==='saves'?<div className="save-actions"><p>每次行动自动保存。手动存档保留一个可随时载入的检查点。</p><button disabled={busy} onClick={()=>void operate('save')}>保存检查点</button><button disabled={busy} onClick={()=>{if(window.confirm('载入将回到上次手动存档，继续？'))void operate('load')}}>载入检查点</button><button disabled={busy} onClick={()=>void exportFile()}>导出存档 JSON</button><button disabled={busy} onClick={()=>jsonRef.current?.click()}>导入 JSON</button><small>导出包含 GM 隐藏数据，适合备份或迁移。</small><button className="quiet" disabled={busy} onClick={()=>setEntered(false)}>返回启动页</button></div>:<>{ActivePanel?<ActivePanel view={view} busy={busy} routineAuto={routineAuto} routineJob={routineJob} pauseRoutine={()=>void pauseRoutine()} acknowledgeTask={async(id,outcome)=>{if(view)setView(await request<PublicView>('routine/tasks/'+id+'/acknowledge',{game_id:view.game_id,expected_revision:view.revision,outcome}));}} onOpenLogs={()=>selectTab('logs')} configureCalendar={async(calendar)=>{if(view){setView(await request<PublicView>('calendar',{calendar,game_id:view.game_id,expected_revision:view.revision}));}}} act={a=>void act(a)} uploadAvatar={uploadAvatar} clearAvatar={clearAvatar} uploadVisualAsset={uploadVisualAsset} importCharacterCard={importCharacterCard} onSelectCharacter={openCharacter}/>:null}</>}</>}</section></div></aside></div><section className="mobile-more" aria-label="更多面板"><h2>世界与设置</h2><div>{panels.filter(p=>panelRegistry[p.id]).map(p=><button key={p.id} onClick={()=>selectTab(p.id)}>{p.label}</button>)}</div></section><nav className="mobile-nav" aria-label="手机快捷导航"><button type="button" onClick={()=>{setMobilePage("game");requestAnimationFrame(()=>storyRef.current?.scrollIntoView({block:"start"}));}}>游戏</button>{mobilePrimary.map(panel=><button type="button" key={panel.id} className={tab===panel.id?'active':''} onClick={()=>selectTab(panel.id)}>{panel.label}</button>)}<button type="button" onClick={()=>setMobilePage("more")}>更多</button></nav></>:<section className="welcome"><h1>没有已载入的世界。</h1><button onClick={()=>setEntered(false)}>返回启动页</button></section>}
      {providerOpen&&<div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)setProviderOpen(false)}}><section className="provider-modal"><div className="modal-title"><div><span className="eyebrow">AI PROVIDER</span><h2>选择模型来源</h2></div><button className="quiet" onClick={()=>setProviderOpen(false)}>关闭</button></div><div className="provider-options">{providers?.providers.map(p=><button key={p.id} className={`provider-option ${providerId===p.id?'selected':''}`} onClick={()=>{setProviderId(p.id);setProviderModel(p.default_model??'');setProviderBase('')}}><strong>{p.label}</strong><small>{p.note}</small></button>)}</div>{selectedProvider?.requires_api_key&&<label className="provider-field">API Key<input type="password" value={providerKey} onChange={e=>setProviderKey(e.target.value)} placeholder={providers?.current?.provider===providerId&&providers.current.api_key_configured?'已配置；留空继续使用当前 Key':'输入 API Key 或留空使用环境变量'}/><small>Key 永远不会从服务端返回到浏览器。{providers?.current?.provider===providerId&&providers.current.api_key_configured?' 当前服务端已有可用 Key。':''}</small></label>}<label className="provider-field">模型<input value={providerModel} onChange={e=>setProviderModel(e.target.value)} placeholder={selectedProvider?.default_model??'填写模型名'}/></label>{selectedProvider?.supports_base_url&&<label className="provider-field">Base URL<input value={providerBase} onChange={e=>setProviderBase(e.target.value)} placeholder="https://example.com/v1"/></label>}<label className="provider-save"><input type="checkbox" checked={providerPersist} onChange={e=>setProviderPersist(e.target.checked)}/><span><strong>保存在这台电脑</strong><small>保存到本机服务端 data/secrets；不进入存档、浏览器 storage 或 Git。手机和电脑连接同一服务时会共用此配置。</small></span></label><div className="provider-actions"><button disabled={busy} onClick={()=>void applyProvider()}>应用 Provider</button>{providers?.current?.saved_provider&&<button type="button" className="quiet" disabled={busy} onClick={()=>void forgetProvider()}>忘记本机保存</button>}</div><p className="provider-note">Codex 模式走 ChatGPT 登录态；API 模式走各自 API 额度。Provider 状态由服务器统一维护，其他已打开的手机/电脑页面会自动同步。</p></section></div>}
      <input ref={jsonRef} hidden type="file" accept=".json,application/json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void loadJson(f).catch(err=>showMessage((err as Error).message,'error'))}}/><input ref={promptRef} hidden type="file" accept=".txt,.md,.json,text/plain,text/markdown,application/json" onChange={e=>{const f=e.target.files?.[0];e.target.value='';if(f)void loadPrompt(f).catch(err=>showMessage((err as Error).message,'error'))}}/>
    </main>{!(entered&&view)&&<footer>AGENT GAME FRAMEWORK <span>本地存档 · 行动驱动 · 持续世界</span></footer>}
  </div>;
}
