import {useEffect,useRef,useState} from 'react';
import type {AvatarCropMetadata} from '../shared/avatar.js';
export function cropGeometry(width:number,height:number,crop:Pick<AvatarCropMetadata,'scale'|'offset_x'|'offset_y'>){
  const side=Math.min(width,height)/crop.scale;
  return {side,x:Math.max(0,Math.min(width-side,(width-side)/2-crop.offset_x*side)),y:Math.max(0,Math.min(height-side,(height-side)/2-crop.offset_y*side))};
}
export function AvatarCropEditor({source,initial,onCancel,onSave}:{source:string;initial?:AvatarCropMetadata;onCancel:()=>void;onSave:(file:File,crop:AvatarCropMetadata)=>Promise<void>}){
  const image=useRef<HTMLImageElement|null>(null),preview=useRef<HTMLCanvasElement>(null),pointers=useRef(new Map<number,{x:number;y:number}>());
  const [size,setSize]=useState({width:0,height:0}),[crop,setCrop]=useState<AvatarCropMetadata>(initial?.source_asset_id===source?initial:{crop_version:1,source_asset_id:source,scale:1,offset_x:0,offset_y:0}),[busy,setBusy]=useState(false),[error,setError]=useState('');
  const maxZoom=Math.max(4,Math.min(100,Math.min(size.width,size.height)/24));
  const normalize=(c:AvatarCropMetadata)=>({...c,scale:Math.max(1,Math.min(maxZoom,c.scale)),offset_x:Math.max(-(size.width/Math.min(size.width,size.height)*c.scale-1)/2,Math.min((size.width/Math.min(size.width,size.height)*c.scale-1)/2,c.offset_x)),offset_y:Math.max(-(size.height/Math.min(size.width,size.height)*c.scale-1)/2,Math.min((size.height/Math.min(size.width,size.height)*c.scale-1)/2,c.offset_y))});
  useEffect(()=>{const img=new Image();img.onload=()=>{image.current=img;setSize({width:img.naturalWidth,height:img.naturalHeight});};img.onerror=()=>setError('无法读取全身图');img.src='/api/visual/'+encodeURIComponent(source);return()=>{img.onload=null;img.onerror=null;};},[source]);
  useEffect(()=>{const context=preview.current?.getContext('2d');if(!context||!image.current||!size.width)return;const g=cropGeometry(size.width,size.height,crop);context.clearRect(0,0,256,256);context.drawImage(image.current,g.x,g.y,g.side,g.side,0,0,256,256);},[size,crop]);
  function zoom(factor:number){if(!size.width)return;setCrop(c=>{const scale=Math.max(1,Math.min(maxZoom,c.scale*factor));return normalize({...c,scale,offset_x:c.offset_x*scale/c.scale,offset_y:c.offset_y*scale/c.scale});});}
  async function save(){if(!image.current)return;setBusy(true);try{const canvas=document.createElement('canvas');canvas.width=canvas.height=512;const g=cropGeometry(size.width,size.height,crop);canvas.getContext('2d')!.drawImage(image.current,g.x,g.y,g.side,g.side,0,0,512,512);const blob=await new Promise<Blob>((resolve,reject)=>canvas.toBlob(b=>b?resolve(b):reject(Error('无法生成头像')),'image/png'));await onSave(new File([blob],'avatar.png',{type:'image/png'}),crop);onCancel();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <div className="modal-backdrop crop-backdrop"><section className="crop-dialog" role="dialog" aria-modal="true" aria-label="调整头像"><h2>调整头像</h2><p>拖动图片；滚轮、双指或滑杆缩放。右侧预览实时更新。</p><div className="crop-workspace"><div className="crop-stage" onWheel={e=>{zoom(Math.exp(-e.deltaY*.002));}} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});}} onPointerMove={e=>{const old=pointers.current.get(e.pointerId);if(!old||!size.width)return;const other=[...pointers.current.entries()].find(([id])=>id!==e.pointerId)?.[1];if(other){const before=Math.hypot(old.x-other.x,old.y-other.y),after=Math.hypot(e.clientX-other.x,e.clientY-other.y);if(before>5)zoom(after/before);}else{const box=e.currentTarget.clientWidth;setCrop(c=>normalize({...c,offset_x:c.offset_x+(e.clientX-old.x)/box,offset_y:c.offset_y+(e.clientY-old.y)/box}));}pointers.current.set(e.pointerId,{x:e.clientX,y:e.clientY});}} onPointerUp={e=>pointers.current.delete(e.pointerId)} onPointerCancel={e=>pointers.current.delete(e.pointerId)}>
      {!!size.width&&<img draggable={false} alt="头像裁剪原图" src={'/api/visual/'+encodeURIComponent(source)} style={{width:`${size.width/Math.min(size.width,size.height)*crop.scale*100}%`,height:`${size.height/Math.min(size.width,size.height)*crop.scale*100}%`,left:`${(0.5+crop.offset_x)*100}%`,top:`${(0.5+crop.offset_y)*100}%`}}/>}<div className="crop-mask"/></div><canvas ref={preview} width={256} height={256} className="crop-preview" aria-label="实时头像预览"/></div>
      <label>缩放<input aria-label="头像缩放" type="range" min={1} max={maxZoom} step={.01} value={crop.scale} disabled={!size.width} onChange={e=>zoom(Number(e.target.value)/crop.scale)}/></label><small className="crop-hint">拖动图片调整位置，滚轮、双指或滑杆缩放。</small>{error&&<p role="alert">{error}</p>}<div className="button-row"><button disabled={busy||!size.width} onClick={()=>void save()}>确定</button><button className="quiet" disabled={busy} onClick={onCancel}>取消</button><button className="quiet" disabled={busy} onClick={()=>setCrop({crop_version:1,source_asset_id:source,scale:1,offset_x:0,offset_y:0})}>重置</button></div></section></div>;
}
