import {useEffect,useMemo,useState} from 'react';
import type {DevelopmentTask} from '../extensions/tasks.js';
import type {PublicView} from '../shared/contracts.js';
import {request,clientRequestId} from './api.js';
import {developmentProjection,type DevelopmentProjection} from '../system/development-status.js';
import {draftSlot,loadDevelopmentWorkspace,saveDevelopmentDraft,saveDevelopmentWorkspace} from './development-workspace.js';
import {sanitizePlayerText} from '../system/player-copy.js';
import {developmentPlayerView} from '../system/development-copy.js';
import {ClarificationCard} from './ClarificationCard.js';

const running=new Set<DevelopmentTask['status']>(['planning','developing','testing','repairing']);
const ended=new Set<DevelopmentTask['status']>(['installed','failed','cancelled']);
function secondsSince(value?:string){if(!value)return null;const n=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/1000));return Number.isFinite(n)?n:null;}
function duration(seconds:number|null){if(seconds===null)return '未知';if(seconds<60)return `${seconds} 秒`;const minutes=Math.floor(seconds/60),rest=seconds%60;return minutes<60?`${minutes} 分 ${rest} 秒`:`${Math.floor(minutes/60)} 小时 ${minutes%60} 分`;}
function statusCopy(task:DevelopmentTask){
 if(running.has(task.status))return {kind:'running',title:'正在开发',instruction:'你现在不需要做任何操作，后台会继续处理。'};
 if(task.status==='waiting_for_user')return {kind:'waiting',title:'需要你的回答',instruction:'开发已暂停，回答下面的问题后会继续。'};
 if(task.status==='waiting_for_core_approval'||task.status==='ready_for_preview')return {kind:'approval',title:'等待你的确认',instruction:task.status==='waiting_for_core_approval'?'代码还没有开始修改，确认后才会继续。':'候选已验证，确认后才会安装。'};
 if(task.status==='failed')return {kind:'failed',title:'开发失败',instruction:'后台已经停止，不会自行继续。'};
 if(task.status==='installed')return {kind:'completed',title:'开发完成',instruction:'功能已经安装，可以在世界中使用或继续提出修改。'};
 if(task.status==='paused')return {kind:'paused',title:'开发已暂停',instruction:'进度和候选工作区已保留，可以继续。'};
 return {kind:'paused',title:'任务已取消',instruction:'历史和产物仍然保留。'};
}

export function DevelopmentPanel({view,onView,taskId,onSelect,onStatus,extensionId}:{view:PublicView;onView?:(v:PublicView)=>void;taskId?:string|null;onSelect?:(id:string)=>void;onStatus?:(status:DevelopmentProjection,detail?:{name:string;requiresAnswer:boolean})=>void;extensionId?:string}){
 const initial=loadDevelopmentWorkspace(view.game_id),initialTask=taskId??initial.active_task_id??'';
 const [tasks,setTasks]=useState<DevelopmentTask[]>([]),[selected,setSelected]=useState(initialTask),[input,setInput]=useState(initial.drafts[draftSlot(initialTask)]??''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[advancedOpen,setAdvancedOpen]=useState(initial.advanced_open),[pendingNew,setPendingNew]=useState(false),[hidden,setHidden]=useState(initial.hidden_task_ids),[showHidden,setShowHidden]=useState(initial.show_hidden_tasks),[onlyActive,setOnlyActive]=useState(initial.only_active),[,setClock]=useState(0);
 const visible=useMemo(()=>tasks.filter(task=>!hidden.includes(task.id)&&(!onlyActive||!ended.has(task.status))),[tasks,hidden,onlyActive]);
 const hiddenTasks=tasks.filter(task=>hidden.includes(task.id));
 const choose=(id:string,saveCurrent=true)=>{if(saveCurrent)saveDevelopmentDraft(view.game_id,selected,input);const saved=saveDevelopmentWorkspace(view.game_id,{active_task_id:id||null});setSelected(id);setInput(saved.drafts[draftSlot(id)]??'');setPendingNew(false);if(id)onSelect?.(id);};
 useEffect(()=>{if(taskId&&taskId!==selected)choose(taskId);},[taskId]);
 useEffect(()=>{const saved=loadDevelopmentWorkspace(view.game_id),id=taskId??saved.active_task_id??'';setSelected(id);setInput(saved.drafts[draftSlot(id)]??'');setAdvancedOpen(saved.advanced_open);setHidden(saved.hidden_task_ids);setShowHidden(saved.show_hidden_tasks);setOnlyActive(saved.only_active);},[view.game_id]);
 useEffect(()=>{let live=true,inFlight=false;const refresh=async()=>{if(inFlight)return;inFlight=true;try{const rows=await request<DevelopmentTask[]>('development/tasks');if(live)setTasks(rows);}catch(e){if(live)setError((e as Error).message);}finally{inFlight=false;}};void refresh();const timer=setInterval(()=>void refresh(),1200);return()=>{live=false;clearInterval(timer);};},[view.game_id]);
 useEffect(()=>{const timer=setInterval(()=>setClock(x=>x+1),1000);return()=>clearInterval(timer);},[]);
 const task=tasks.find(t=>t.id===selected),preview=task?.preview;
 useEffect(()=>{if(task)onStatus?.(developmentProjection(task),{name:String(task.preview?.name??task.original_request).slice(0,40),requiresAnswer:task.status==='waiting_for_user'});},[task?.id,task?.status,task?.message]);
 useEffect(()=>{if(selected&&!hidden.includes(selected)&&visible.some(t=>t.id===selected))return;if(selected&&(hidden.includes(selected)||onlyActive)){const next=visible[0]?.id??'';if(next!==selected)choose(next);}},[hidden,onlyActive,tasks.length]);
 async function command(path:string,body:unknown){setBusy(true);setError('');try{const result=await request<DevelopmentTask|PublicView>(path,body);if('revision' in result&&'entities' in result)onView?.(result);else{const t=result as DevelopmentTask;setSelected(t.id);saveDevelopmentWorkspace(view.game_id,{active_task_id:t.id});onSelect?.(t.id);}setTasks(await request<DevelopmentTask[]>('development/tasks'));saveDevelopmentDraft(view.game_id,selected,'');setInput('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function hideTask(id:string){const next=[...new Set([...hidden,id])];setHidden(next);saveDevelopmentWorkspace(view.game_id,{hidden_task_ids:next});if(selected===id){const replacement=visible.find(t=>t.id!==id)?.id??'';choose(replacement);}}
 function restoreTask(id:string){const next=hidden.filter(value=>value!==id);setHidden(next);saveDevelopmentWorkspace(view.game_id,{hidden_task_ids:next});}
 function hideEnded(){const next=[...new Set([...hidden,...tasks.filter(task=>ended.has(task.status)).map(task=>task.id)])];setHidden(next);saveDevelopmentWorkspace(view.game_id,{hidden_task_ids:next});}
 const player=task?developmentPlayerView(task):null,status=task?statusCopy(task):null,lastActivity=secondsSince(task?.last_activity_at??task?.history.at(-1)?.at),elapsed=secondsSince(task?.started_at??task?.history[0]?.at);
 return <section className="development-panel"><header className="development-heading"><div><h3>功能开发</h3><p>描述想实现的体验。系统会保存进度，并在需要你决定时明确提醒。</p></div></header>
 <div className="development-task-toolbar"><label>开发任务<select aria-label="开发任务" value={visible.some(t=>t.id===selected)?selected:''} onChange={e=>{const id=e.target.value;if(!id&&task&&input.trim())setPendingNew(true);else choose(id);}}><option value="">创建新任务</option>{visible.map(t=><option key={t.id} value={t.id}>{t.preview?.name??t.original_request.slice(0,45)} · {developmentProjection(t).label}</option>)}</select></label><button type="button" className="quiet" onClick={()=>{const value=!showHidden;setShowHidden(value);saveDevelopmentWorkspace(view.game_id,{show_hidden_tasks:value});}}>管理任务</button></div>
 {tasks.length>0&&<details className="task-organizer"><summary>整理任务</summary><label className="compact-check"><input type="checkbox" checked={onlyActive} onChange={e=>{setOnlyActive(e.target.checked);saveDevelopmentWorkspace(view.game_id,{only_active:e.target.checked});}}/>仅显示进行中</label><button type="button" className="quiet" onClick={hideEnded}>隐藏所有已结束任务</button><div className="task-organizer-list">{tasks.filter(t=>!hidden.includes(t.id)).map(t=><div key={t.id} className={t.id===selected?'selected':''}><button type="button" className="task-name" onClick={()=>choose(t.id)}>{t.preview?.name??t.original_request.slice(0,45)}<small>{developmentProjection(t).label}</small></button><button type="button" className="task-hide" aria-label={`隐藏任务 ${t.preview?.name??t.original_request}`} title="从列表隐藏，不会停止后台任务" onClick={()=>hideTask(t.id)}>×</button></div>)}</div></details>}
 {showHidden&&<section className="hidden-tasks" aria-label="已隐藏任务"><h4>已隐藏任务</h4>{hiddenTasks.length?hiddenTasks.map(t=><div className="item-row" key={t.id}><span>{t.preview?.name??t.original_request.slice(0,45)}</span><button type="button" className="quiet" onClick={()=>restoreTask(t.id)}>恢复</button></div>):<p className="empty">没有已隐藏任务。</p>}</section>}
 {pendingNew&&<div className="system-hint" role="alert"><p>当前还有未提交内容。</p><div className="button-row compact"><button type="button" onClick={()=>choose('')}>保留草稿并新建</button><button type="button" className="quiet" onClick={()=>setPendingNew(false)}>继续当前任务</button><button type="button" className="quiet" onClick={()=>{saveDevelopmentDraft(view.game_id,selected,'');choose('',false);}}>丢弃草稿并新建</button></div></div>}
 <label>{task?'补充要求或继续修改':'你希望增加或修改什么？'}<textarea aria-label="开发要求" value={input} onChange={e=>{setInput(e.target.value);saveDevelopmentDraft(view.game_id,selected,e.target.value);}} maxLength={3000}/></label>
 <button className="primary" disabled={busy||!input.trim()} onClick={()=>void command(task?'development/tasks/'+task.id+'/revise':'development/tasks',task?{request:input}:{request:input,request_id:clientRequestId(),...(extensionId?{extension_id:extensionId}:{})})}>{task?'提交修改要求':'开始开发'}</button>
 {error&&<p role="alert" className="development-error">{error}</p>}
 {task&&status&&<article className="development-task"><section className={`development-status ${status.kind}`} role="status"><div><span className="status-kicker">PLAYER STATUS</span><h4>{status.title}</h4><p>{status.instruction}</p></div><dl><div><dt>当前阶段</dt><dd>{task.current_phase?developmentProjection({...task,status:task.current_phase as DevelopmentTask['status']}).label:developmentProjection(task).label}</dd></div><div><dt>已运行</dt><dd>{duration(elapsed)}</dd></div><div><dt>最近进展</dt><dd>{lastActivity===null?'未知':lastActivity<10?'刚刚':`${duration(lastActivity)}前`}</dd></div><div><dt>后台任务</dt><dd>{task.active_job??(running.has(task.status)?'仍在运行':'当前没有运行')}</dd></div></dl><p className="latest-progress">{sanitizePlayerText(task.latest_progress_message??player?.message??task.message)}</p>{lastActivity!==null&&lastActivity>90&&running.has(task.status)&&<p className="stale-activity">已经较长时间没有新进展，可以展开高级开发详情查看记录。</p>}</section>
 {task.status==='waiting_for_user'&&<ClarificationCard question={player?.question??player?.message??task.message} options={player?.options??[]} onAnswer={answer=>{if(answer.trim())void command('development/tasks/'+task.id+'/revise',{request:answer.trim()});}} disabled={busy}/>}
 <section className="development-progress"><div className="section-heading"><h4>当前进度</h4><span>已验证 {task.milestones.filter(m=>m.status==='passed').length}/{task.milestones.length}</span></div><ol>{task.milestones.map(m=><li key={m.id} className={m.status}><span>{m.title}</span><b>{m.status==='passed'?'已验证':m.status==='failed'?'等待修复':'待处理'}</b></li>)}</ol></section>
 {preview&&task.status==='ready_for_preview'&&<section className="development-result" aria-label="功能预览"><h4>{sanitizePlayerText(preview.name,'这个功能')}</h4><p>{sanitizePlayerText(preview.requirements.join('；'),'')}</p><p>使用方式：{sanitizePlayerText(preview.usage,'')}</p><p>完成后会新增：{sanitizePlayerText(preview.ui.join('、'),'')}</p><button className="primary" disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/install',{candidate_version:task.current_version,confirmed:true,migration_confirmed:preview.migration.length>0,game_id:view.game_id,expected_revision:view.revision,request_id:clientRequestId()})}>{preview.migration.length?'确认迁移并安装':'确认安装候选'}</button></section>}
 {task.core_proposal&&task.status==='waiting_for_core_approval'&&<section className="development-decision" aria-label="核心能力提案"><h4>需要补充框架能力</h4><p>{sanitizePlayerText(task.core_proposal.problem,'这个需求需要框架增加一项通用能力。')}</p><p>确认后会在隔离工作区开始开发；候选通过测试前不会安装。</p><button className="primary" disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/approve-core',{confirmed:true})}>批准并继续</button></section>}
 {task.core_execution?.status==='candidate_ready'&&!task.core_install&&<section className="development-decision"><h4>核心候选已验证</h4><p>候选尚未安装。确认后系统会执行受控安装，并要求重启验证。</p><button className="primary" disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/install-core',{confirmed:true})}>安装核心候选</button></section>}
 {task.status==='installed'&&<section className="development-result"><h4>已安装 {task.installed_version}</h4><p>功能处于可用状态。可以回到世界体验，或在上方补充新的修改要求。</p></section>}
 <div className="button-row secondary-actions">{['paused','failed'].includes(task.status)&&!task.capability_gaps.length&&<button disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/resume',{})}>{task.status==='failed'?'重试':'继续开发'}</button>}{!['installed','cancelled'].includes(task.status)&&<button className="quiet" disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/cancel',{})}>取消并保留进度</button>}</div>
 <details open={advancedOpen} onToggle={e=>{const open=e.currentTarget.open;setAdvancedOpen(open);saveDevelopmentWorkspace(view.game_id,{advanced_open:open});}}><summary>高级开发详情</summary><pre>{JSON.stringify({workspace:task.workspace,capability_gaps:task.capability_gaps,core_proposal:task.core_proposal,core_recovery:task.core_recovery,core_execution:task.core_execution,core_install:task.core_install,artifacts:task.artifacts,test_results:task.test_results,history:task.history},null,2)}</pre></details>
 </article>}</section>;
}
