import {useEffect,useState} from 'react';
import type {DevelopmentTask} from '../extensions/tasks.js';
import type {PublicView} from '../shared/contracts.js';
import {request,clientRequestId} from './api.js';
import {developmentProjection,type DevelopmentProjection} from '../system/development-status.js';
import {draftSlot,loadDevelopmentWorkspace,saveDevelopmentDraft,saveDevelopmentWorkspace} from './development-workspace.js';
import {sanitizePlayerText} from '../system/player-copy.js';
export function DevelopmentPanel({view,onView,taskId,onSelect,onStatus,extensionId}:{view:PublicView;onView?:(v:PublicView)=>void;taskId?:string|null;onSelect?:(id:string)=>void;onStatus?:(status:DevelopmentProjection)=>void;extensionId?:string}){
 const initial=loadDevelopmentWorkspace(view.game_id),initialTask=taskId??initial.active_task_id??'';
 const [tasks,setTasks]=useState<DevelopmentTask[]>([]),[selected,setSelected]=useState(initialTask),[input,setInput]=useState(initial.drafts[draftSlot(initialTask)]??''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[advancedOpen,setAdvancedOpen]=useState(initial.advanced_open),[pendingNew,setPendingNew]=useState(false);
 const choose=(id:string,saveCurrent=true)=>{if(saveCurrent)saveDevelopmentDraft(view.game_id,selected,input);const saved=saveDevelopmentWorkspace(view.game_id,{active_task_id:id||null});setSelected(id);setInput(saved.drafts[draftSlot(id)]??'');setPendingNew(false);if(id)onSelect?.(id);};
 useEffect(()=>{if(taskId&&taskId!==selected)choose(taskId);},[taskId]);
 useEffect(()=>{const saved=loadDevelopmentWorkspace(view.game_id),id=taskId??saved.active_task_id??'';setSelected(id);setInput(saved.drafts[draftSlot(id)]??'');setAdvancedOpen(saved.advanced_open);},[view.game_id]);
 useEffect(()=>{let live=true,inFlight=false;const refresh=async()=>{if(inFlight)return;inFlight=true;try{const rows=await request<DevelopmentTask[]>('development/tasks');if(live)setTasks(rows);}catch(e){if(live)setError((e as Error).message);}finally{inFlight=false;}};void refresh();const timer=setInterval(()=>void refresh(),1200);return()=>{live=false;clearInterval(timer);};},[view.game_id]);
 const task=tasks.find(t=>t.id===selected),preview=task?.preview;
 useEffect(()=>{if(task)onStatus?.(developmentProjection(task));},[task?.id,task?.status]);
 async function command(path:string,body:unknown){setBusy(true);setError('');try{const result=await request<DevelopmentTask|PublicView>(path,body);if('revision' in result&&'entities' in result)onView?.(result);else{const t=result as DevelopmentTask;setSelected(t.id);saveDevelopmentWorkspace(view.game_id,{active_task_id:t.id});onSelect?.(t.id);}setTasks(await request<DevelopmentTask[]>('development/tasks'));saveDevelopmentDraft(view.game_id,selected,'');setInput('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <section className="development-panel"><h3>功能开发</h3><p>描述目标，确认后再安装。</p>

 <label>开发任务<select aria-label="开发任务" value={selected} onChange={e=>{const id=e.target.value;if(!id&&task&&input.trim())setPendingNew(true);else choose(id);}}><option value="">创建新任务</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.preview?.name??t.original_request.slice(0,45)} · {developmentProjection(t).label}</option>)}</select></label>
 {pendingNew&&<div className="system-hint" role="alert"><p>当前还有未提交内容。</p><div className="button-row compact"><button type="button" onClick={()=>choose('')}>保留草稿并新建</button><button type="button" className="quiet" onClick={()=>setPendingNew(false)}>继续当前任务</button><button type="button" className="quiet" onClick={()=>{saveDevelopmentDraft(view.game_id,selected,'');choose('',false);}}>丢弃草稿并新建</button></div></div>}
 <label>{task?'补充要求或继续修改':'你希望增加或修改什么？'}<textarea aria-label="开发要求" value={input} onChange={e=>{setInput(e.target.value);saveDevelopmentDraft(view.game_id,selected,e.target.value);}} maxLength={3000}/></label>
 <button disabled={busy||!input.trim()} onClick={()=>void command(task?'development/tasks/'+task.id+'/revise':'development/tasks',task?{request:input}:{request:input,request_id:clientRequestId(),...(extensionId?{extension_id:extensionId}:{})})}>{task?'提交修改要求':'开始开发'}</button>
 {error&&<p role="alert">{error}</p>}
 {task&&<article><h4>{developmentProjection(task).label} · 候选 {task.current_version}</h4><p>{task.message}</p><p>本轮尝试 {task.attempts}/{task.budget.max_attempts} · 已验证阶段 {task.milestones.filter(m=>m.status==='passed').length}/{task.milestones.length}{task.installed_version?' · 已安装 '+task.installed_version:''}</p>
 <ol>{task.milestones.map(m=><li key={m.id}>{m.title}：{m.status==='passed'?'已验证':m.status==='failed'?'等待修复':'待处理'}</li>)}</ol>
 {preview&&task.status==='ready_for_preview'&&<section aria-label="功能预览"><h4>{preview.name}</h4><p>{preview.requirements.join('；')}</p><p>使用方式：{preview.usage}</p><p>主要规则：{preview.rules.join('；')}</p><p>新增界面：{preview.ui.join('、')}</p><p>世界接入：{preview.world_integration}</p><p>正史写入：{preview.canonical_writes.join('、')||'无'}</p><p>自有数据：{preview.own_state.join('、')}</p><p>权限：{preview.permissions.join('；')}</p><p>限制：{preview.risk}</p>{preview.migration.length>0&&<p>迁移方案：{preview.migration.join('；')}</p>}<button disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/install',{candidate_version:task.current_version,confirmed:true,migration_confirmed:preview.migration.length>0,game_id:view.game_id,expected_revision:view.revision,request_id:clientRequestId()})}>{preview.migration.length?'确认迁移并安装':'确认安装候选'}</button></section>}
 {task.core_proposal&&<section aria-label="核心能力提案"><h4>需要补充框架能力</h4><p>{sanitizePlayerText(task.core_proposal.problem)}</p><p>影响：{sanitizePlayerText(task.core_proposal.impact.join('、'))}</p><p>迁移：{sanitizePlayerText(task.core_proposal.migration)}</p><p>验证：{sanitizePlayerText(task.core_proposal.tests.join('、'))}</p><p>回滚：{sanitizePlayerText(task.core_proposal.rollback)}</p><p>风险：{sanitizePlayerText(task.core_proposal.risk)}</p><p>批准后会在隔离工作区调用可用的编码后端，并由框架检查 diff、测试与构建；通过的候选仍需完成安装和注册才算可用。</p>{task.status==='waiting_for_core_approval'&&<button disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/approve-core',{confirmed:true})}>批准核心开发提案</button>}</section>}
 <div className="button-row">{['paused','failed'].includes(task.status)&&!task.capability_gaps.length&&<button disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/resume',{})}>继续开发</button>}{!['installed','cancelled'].includes(task.status)&&<button disabled={busy} onClick={()=>void command('development/tasks/'+task.id+'/cancel',{})}>取消并保留进度</button>}</div>
 <details open={advancedOpen} onToggle={e=>{const open=e.currentTarget.open;setAdvancedOpen(open);saveDevelopmentWorkspace(view.game_id,{advanced_open:open});}}><summary>高级开发详情</summary><pre>{JSON.stringify({workspace:task.workspace,capability_gaps:task.capability_gaps,core_proposal:task.core_proposal,artifacts:task.artifacts,test_results:task.test_results,history:task.history},null,2)}</pre></details>
 </article>}</section>;
}
