import {DevelopmentPanel} from './DevelopmentPanel.js';
import {useEffect,useState} from 'react';
import type {PublicView} from '../shared/contracts.js';
import type {ExtensionManifest} from '../extensions/schema.js';
import {request,clientRequestId} from './api.js';

export interface ExtensionIntent {kind:'extension_request'|'extension_open';template:'blackjack'|'turn_based_combat'|'declarative'|null;request:string;extension_id?:string}
interface Installed {id:string;name:string;version:string;enabled:boolean;installed:boolean;available:boolean;can_open:boolean;manifest:ExtensionManifest;warning:string|null;state:any;previous_version:string|null}
const cards=(values:(number|null)[])=>values.map((c,i)=><span className="playing-card" key={i}>{c===null?'背面':['A','2','3','4','5','6','7','8','9','10','J','Q','K'][c%13]+['♠','♥','♦','♣'][Math.floor(c/13)]}</span>);

export function ExtensionPanel({view,intent,onView,showDevelopment=true}:{view:PublicView;intent:ExtensionIntent|null;onView:(v:PublicView)=>void;showDevelopment?:boolean}){
 const [items,setItems]=useState<Installed[]>([]),[selected,setSelected]=useState<string|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[stake,setStake]=useState(0),[editing,setEditing]=useState<string|null>(null),[purging,setPurging]=useState<Installed|null>(null);
 const tx=()=>({game_id:view.game_id,expected_revision:view.revision,request_id:clientRequestId()});
 async function refresh(){setItems(await request<Installed[]>('extensions'));}
 useEffect(()=>{let live=true,inFlight=false;const update=async()=>{if(inFlight)return;inFlight=true;try{const list=await request<Installed[]>('extensions');if(live)setItems(list);}catch(e){if(live)setError((e as Error).message);}finally{inFlight=false;}};void update();const timer=setInterval(()=>void update(),1200);return()=>{live=false;clearInterval(timer);};},[view.game_id]);
 useEffect(()=>{if(intent?.extension_id)setSelected(intent.extension_id);},[intent]);
 async function change(path:string,body:unknown){setBusy(true);setError('');try{onView(await request<PublicView>(path,body));await refresh();}catch(e){setError((e as Error).message);onView(await request<PublicView>('state'));}finally{setBusy(false);}}
 const current=items.find(x=>x.id===selected),playing=current?.state?.phase==='playing',installed=items.filter(item=>item.installed),retained=items.filter(item=>!item.installed);
 const card=(e:Installed)=><article className={`feature-card ${e.enabled?'enabled':'disabled'} ${e.installed?'installed':'retained'}`} key={e.id}>
  <header><div><span className={`feature-status ${e.installed?(e.enabled?'active':'sleeping'):'retained'}`}>{e.installed?(e.enabled?'已启用':'已停用'):'已卸载 · 数据保留'}</span><h4>{e.name}</h4><small>版本 {e.version}</small></div><span className="feature-mark" aria-hidden="true">{e.installed?(e.enabled?'✓':'Ⅱ'):'↺'}</span></header>
  <p>{e.warning??e.manifest.description}</p>
  <div className="feature-primary-actions">{e.installed&&e.enabled&&<button className="quiet" disabled={busy} onClick={()=>void change('extensions/'+e.id+'/disable',tx())}>停用</button>}{e.installed&&!e.enabled&&<button disabled={busy} onClick={()=>void change('extensions/'+e.id+'/enable',tx())}>启用</button>}{!e.installed&&<button disabled={busy||!e.available} onClick={()=>void change('extensions/'+e.id+'/reinstall',tx())}>重新安装并恢复数据</button>}{e.installed&&<button className="quiet" disabled={!e.can_open} onClick={()=>setSelected(e.id)}>查看玩法</button>}</div>
  {!e.can_open&&e.enabled&&e.installed&&<small>当前场景不符合此功能的启用条件。</small>}
  <details className="feature-menu"><summary aria-label={`${e.name} 更多操作`}>更多操作 ···</summary><div className="feature-menu-actions"><button className="quiet" onClick={()=>setEditing(e.id)}>修改这个功能</button>{e.installed&&e.previous_version&&<button className="quiet" disabled={busy} onClick={()=>void change('extensions/'+e.id+'/rollback',tx())}>回滚到 {e.previous_version}</button>}{e.installed&&<button className="danger-quiet" disabled={busy} onClick={()=>void change('extensions/'+e.id+'/uninstall',tx())}>卸载并保留数据</button>}{!e.installed&&<button className="danger-quiet" disabled={busy} onClick={()=>setPurging(e)}>永久删除保留数据</button>}</div></details>
 </article>;
 return <div className="extension-panel">{showDevelopment&&<header className="extension-intro"><span className="section-kicker">EXTENSION STUDIO</span><h3>功能扩展</h3><p>描述想增加的体验。每个功能都有独立版本、状态和数据生命周期。</p></header>}
 {(showDevelopment||editing)&&<DevelopmentPanel key={editing??'new'} view={view} onView={onView} extensionId={editing??selected??undefined}/>}
 {error&&<p role="alert" className="development-error">{error}</p>}
 <section className="feature-library" aria-label="已安装功能"><div className="section-heading"><div><span className="section-kicker">ACTIVE LIBRARY</span><h3>已安装功能</h3></div><span>{installed.length} 项</span></div>{installed.length?<div className="feature-grid">{installed.map(card)}</div>:<p className="empty">还没有安装功能。</p>}</section>
 {retained.length>0&&<section className="feature-library retained-library" aria-label="已卸载功能"><div className="section-heading"><div><span className="section-kicker">RETAINED DATA</span><h3>已卸载功能</h3></div><span>{retained.length} 项</span></div><p className="muted">玩法已移除，原状态仍保留，可随时重新安装。</p><div className="feature-grid">{retained.map(card)}</div></section>}
 {current&&current.installed&&current.manifest.template==='declarative'&&<section className="minigame" aria-label={current.manifest.name}><div className="item-row"><h3>{current.name}</h3><button className="quiet" onClick={()=>setSelected(null)}>关闭界面</button></div><p>{current.manifest.description}</p><ul className="declarative-values">{current.manifest.fields.filter(field=>(field.scope??'extension')==='extension').map(field=><li key={field.key}>{field.label??field.key}：{String(current.state?.values?.[field.key]??field.initial)}</li>)}</ul>{current.manifest.fields.some(field=>field.scope==='entity')&&<p className="muted">人物属性会显示在对应人物详情中，每个人物独立保存。</p>}<div className="button-row">{current.manifest.declarative_actions.map(action=><button disabled={busy||!current.can_open} key={action.id} onClick={()=>void change('extensions/'+current.id+'/action',{...tx(),action:{type:action.id}})}>{action.label}</button>)}</div><small>声明式扩展只能修改自己的状态命名空间，不写入世界正史。</small></section>}
 {current&&current.installed&&current.manifest.template!=='declarative'&&<section className="minigame" aria-label={current.manifest.template==='blackjack'?'21 点牌桌':'回合制训练'}><div className="item-row"><h3>{current.name}</h3><button className="quiet" onClick={()=>setSelected(null)}>关闭界面，保留本局</button></div>{current.manifest.template==='blackjack'?<><p>庄家</p><div className="cards">{cards(current.state?.dealer??[])}</div><p>你的手牌</p><div className="cards">{cards(current.state?.player??[])}</div>{!playing&&current.manifest.allow_betting&&<label>下注（0 为练习）<input aria-label="下注金额" type="number" min={0} max={current.manifest.max_stake} value={stake} onChange={e=>setStake(Number(e.target.value))}/></label>}</>:<><p>玩家生命：{String(view.entities.find(e=>e.id===view.player_id)?.components.condition?.hp??'未定义')}</p><p>训练对手生命：{current.state?.enemy_hp??20}</p><p>训练会造成真实生命变化；撤退不会产生奖励。</p></>}<p>{current.state?.result}</p><div className="button-row">{(playing?(current.manifest.template==='blackjack'?['hit','stand']:['attack','flee']):['start']).map(type=><button disabled={busy||!current.can_open} key={type} onClick={()=>void change('extensions/'+current.id+'/action',{...tx(),action:{type,...(type==='start'&&current.manifest.template==='blackjack'?{stake:current.manifest.allow_betting?stake:0,currency:Object.keys(view.currencies)[0]}:{})}})}>{({start:'新一局',hit:'要牌',stand:'停牌',attack:'攻击',flee:'逃跑'} as Record<string,string>)[type]}</button>)}</div><small>刷新或关闭界面保留未完成局；不会自动重新扣费或结算。</small></section>}
 {purging&&<div className="confirmation-backdrop" role="presentation" onMouseDown={event=>{if(event.currentTarget===event.target)setPurging(null);}}><section className="confirmation-dialog" role="alertdialog" aria-modal="true" aria-labelledby="purge-title"><span className="danger-kicker">PERMANENT ACTION</span><h3 id="purge-title">永久删除「{purging.name}」的数据？</h3><p>扩展已经卸载。继续会删除它保留的状态和历史版本信息，之后无法恢复。</p><div className="button-row"><button className="danger" disabled={busy} onClick={()=>void change('extensions/'+purging.id+'/purge',tx()).then(()=>setPurging(null))}>确认永久删除</button><button className="quiet" disabled={busy} onClick={()=>setPurging(null)}>取消</button></div></section></div>}
 </div>;
}
